// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="net,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.664500,HLS_SYN_LAT=29162,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=3508,HLS_SYN_LUT=3892}" *)

module net (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST
);

parameter    ap_ST_st1_fsm_0 = 39'b1;
parameter    ap_ST_st2_fsm_1 = 39'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 39'b100;
parameter    ap_ST_pp0_stg1_fsm_3 = 39'b1000;
parameter    ap_ST_pp0_stg2_fsm_4 = 39'b10000;
parameter    ap_ST_pp0_stg3_fsm_5 = 39'b100000;
parameter    ap_ST_pp0_stg4_fsm_6 = 39'b1000000;
parameter    ap_ST_pp0_stg5_fsm_7 = 39'b10000000;
parameter    ap_ST_pp0_stg6_fsm_8 = 39'b100000000;
parameter    ap_ST_pp0_stg7_fsm_9 = 39'b1000000000;
parameter    ap_ST_pp0_stg8_fsm_10 = 39'b10000000000;
parameter    ap_ST_pp0_stg9_fsm_11 = 39'b100000000000;
parameter    ap_ST_pp0_stg10_fsm_12 = 39'b1000000000000;
parameter    ap_ST_pp0_stg11_fsm_13 = 39'b10000000000000;
parameter    ap_ST_pp0_stg12_fsm_14 = 39'b100000000000000;
parameter    ap_ST_pp0_stg13_fsm_15 = 39'b1000000000000000;
parameter    ap_ST_pp0_stg14_fsm_16 = 39'b10000000000000000;
parameter    ap_ST_pp0_stg15_fsm_17 = 39'b100000000000000000;
parameter    ap_ST_pp0_stg16_fsm_18 = 39'b1000000000000000000;
parameter    ap_ST_pp0_stg17_fsm_19 = 39'b10000000000000000000;
parameter    ap_ST_pp0_stg18_fsm_20 = 39'b100000000000000000000;
parameter    ap_ST_pp0_stg19_fsm_21 = 39'b1000000000000000000000;
parameter    ap_ST_pp0_stg20_fsm_22 = 39'b10000000000000000000000;
parameter    ap_ST_pp0_stg21_fsm_23 = 39'b100000000000000000000000;
parameter    ap_ST_pp0_stg22_fsm_24 = 39'b1000000000000000000000000;
parameter    ap_ST_pp0_stg23_fsm_25 = 39'b10000000000000000000000000;
parameter    ap_ST_pp0_stg24_fsm_26 = 39'b100000000000000000000000000;
parameter    ap_ST_pp0_stg25_fsm_27 = 39'b1000000000000000000000000000;
parameter    ap_ST_pp0_stg26_fsm_28 = 39'b10000000000000000000000000000;
parameter    ap_ST_pp0_stg27_fsm_29 = 39'b100000000000000000000000000000;
parameter    ap_ST_pp0_stg28_fsm_30 = 39'b1000000000000000000000000000000;
parameter    ap_ST_pp0_stg29_fsm_31 = 39'b10000000000000000000000000000000;
parameter    ap_ST_pp0_stg30_fsm_32 = 39'b100000000000000000000000000000000;
parameter    ap_ST_pp0_stg31_fsm_33 = 39'b1000000000000000000000000000000000;
parameter    ap_ST_pp0_stg32_fsm_34 = 39'b10000000000000000000000000000000000;
parameter    ap_ST_pp0_stg33_fsm_35 = 39'b100000000000000000000000000000000000;
parameter    ap_ST_pp0_stg34_fsm_36 = 39'b1000000000000000000000000000000000000;
parameter    ap_ST_pp0_stg35_fsm_37 = 39'b10000000000000000000000000000000000000;
parameter    ap_ST_st76_fsm_38 = 39'b100000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_25 = 32'b100101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_24 = 32'b100100;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv5_19 = 5'b11001;
parameter    ap_const_lv10_310 = 10'b1100010000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv5_1C = 5'b11100;
parameter    ap_const_lv5_1F = 5'b11111;
parameter    ap_const_lv5_1E = 5'b11110;
parameter    ap_const_lv5_1D = 5'b11101;
parameter    ap_const_lv5_1B = 5'b11011;
parameter    ap_const_lv5_1A = 5'b11010;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv8_54 = 8'b1010100;
parameter    ap_const_lv9_A8 = 9'b10101000;
parameter    ap_const_lv8_55 = 8'b1010101;
parameter    ap_const_lv9_A9 = 9'b10101001;
parameter    ap_const_lv8_56 = 8'b1010110;
parameter    ap_const_lv9_AA = 9'b10101010;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv9_2 = 9'b10;
parameter    ap_const_lv8_FB = 8'b11111011;
parameter    ap_const_lv8_1E = 8'b11110;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv9_34 = 9'b110100;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv9_68 = 9'b1101000;
parameter    ap_const_lv9_35 = 9'b110101;
parameter    ap_const_lv9_69 = 9'b1101001;
parameter    ap_const_lv33_1 = 33'b1;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv8_28 = 8'b101000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_23 = 32'b100011;
parameter    ap_const_lv32_26 = 32'b100110;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg OUTPUT_STREAM_TVALID;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [38:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_56;
reg   [7:0] line_buffer_address0;
reg    line_buffer_ce0;
reg    line_buffer_we0;
reg   [7:0] line_buffer_d0;
wire   [7:0] line_buffer_q0;
reg   [7:0] line_buffer_address1;
reg    line_buffer_ce1;
reg    line_buffer_we1;
reg   [7:0] line_buffer_d1;
wire   [7:0] line_buffer_q1;
reg   [7:0] line_buffer_1_address0;
reg    line_buffer_1_ce0;
reg    line_buffer_1_we0;
reg   [7:0] line_buffer_1_d0;
wire   [7:0] line_buffer_1_q0;
reg   [7:0] line_buffer_1_address1;
reg    line_buffer_1_ce1;
reg    line_buffer_1_we1;
reg   [7:0] line_buffer_1_d1;
wire   [7:0] line_buffer_1_q1;
reg    OUTPUT_STREAM_TDATA_blk_n;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_117;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg   [0:0] compute_2_reg_1727;
reg   [9:0] indvar_flatten_reg_401;
reg   [4:0] row_assign_reg_412;
reg   [4:0] col_assign_reg_423;
reg   [7:0] reg_463;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_4;
reg    ap_sig_143;
reg   [0:0] exitcond_flatten_reg_1499;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_6;
reg    ap_sig_154;
reg   [7:0] reg_468;
wire   [0:0] exitcond_flatten_fu_496_p2;
reg    ap_sig_ioackin_OUTPUT_STREAM_TREADY;
wire   [9:0] indvar_flatten_next_fu_502_p2;
reg   [9:0] indvar_flatten_next_reg_1503;
wire   [4:0] col_assign_mid2_fu_520_p3;
reg   [4:0] col_assign_mid2_reg_1508;
wire   [4:0] row_assign_mid2_fu_554_p3;
reg   [4:0] row_assign_mid2_reg_1515;
wire   [0:0] compute_1_fu_580_p2;
reg   [0:0] compute_1_reg_1520;
wire   [0:0] tmp_42_fu_682_p2;
reg   [0:0] tmp_42_reg_1526;
reg   [0:0] ap_reg_ppstg_tmp_42_reg_1526_pp0_iter1;
wire   [0:0] tmp_61_fu_796_p2;
reg   [0:0] tmp_61_reg_1530;
reg   [0:0] ap_reg_ppstg_tmp_61_reg_1530_pp0_iter1;
wire   [0:0] tmp_79_fu_913_p2;
reg   [0:0] tmp_79_reg_1539;
reg   [0:0] ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1;
wire   [0:0] tmp_98_fu_1027_p2;
reg   [0:0] tmp_98_reg_1543;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1;
wire   [7:0] tmp_7_fu_1047_p2;
reg   [7:0] tmp_7_reg_1547;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_3;
reg    ap_sig_216;
wire  signed [8:0] tmp_7_cast5_fu_1053_p1;
reg  signed [8:0] tmp_7_cast5_reg_1554;
reg   [7:0] line_buffer_1_addr_reg_1562;
reg   [7:0] line_buffer_1_addr_2_reg_1568;
wire   [4:0] col_fu_1079_p2;
reg   [4:0] col_reg_1574;
reg   [7:0] line_buffer_1_addr_3_reg_1579;
reg   [7:0] line_buffer_1_addr_5_reg_1584;
reg   [7:0] line_buffer_1_addr_6_reg_1589;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_5;
reg    ap_sig_241;
reg   [7:0] line_buffer_1_addr_8_reg_1595;
reg   [7:0] line_buffer_1_load_2_reg_1601;
reg   [7:0] line_buffer_1_load_3_reg_1606;
reg   [7:0] tmp_101_reg_1611;
reg    ap_sig_cseq_ST_pp0_stg5_fsm_7;
reg    ap_sig_257;
wire   [7:0] img_input_data_stream_0_V_dout;
wire    img_input_data_stream_0_V_empty_n;
reg    img_input_data_stream_0_V_read;
wire   [7:0] img_input_data_stream_1_V_dout;
wire    img_input_data_stream_1_V_empty_n;
reg    img_input_data_stream_1_V_read;
wire   [7:0] img_input_data_stream_2_V_dout;
wire    img_input_data_stream_2_V_empty_n;
reg    img_input_data_stream_2_V_read;
reg    ap_sig_279;
reg   [7:0] tmp_102_reg_1618;
reg   [7:0] tmp_103_reg_1626;
reg   [7:0] output_conv_1_1_1_load_reg_1634;
reg    ap_sig_cseq_ST_pp0_stg7_fsm_9;
reg    ap_sig_295;
wire   [7:0] tmp_33_1_1_2_2_i_fu_1172_p2;
reg   [7:0] tmp_33_1_1_2_2_i_reg_1639;
wire   [7:0] tmp4_fu_1181_p2;
reg   [7:0] tmp4_reg_1644;
wire   [7:0] output_conv_1_0_fu_1221_p3;
reg   [7:0] output_conv_1_0_reg_1649;
reg    ap_sig_cseq_ST_pp0_stg8_fsm_10;
reg    ap_sig_313;
reg   [7:0] ap_reg_ppstg_output_conv_1_0_reg_1649_pp0_iter1;
wire   [7:0] output_conv_1_1_fu_1228_p3;
reg   [7:0] output_conv_1_1_reg_1656;
reg   [7:0] ap_reg_ppstg_output_conv_1_1_reg_1656_pp0_iter1;
wire   [0:0] tmp_5_fu_1248_p2;
reg   [0:0] tmp_5_reg_1662;
reg    ap_sig_cseq_ST_pp0_stg35_fsm_37;
reg    ap_sig_329;
reg   [31:0] col_c2_1_load_1_reg_1671;
wire   [8:0] tmp_17_cast_fu_1281_p3;
reg   [8:0] tmp_17_cast_reg_1678;
reg   [7:0] line_buffer_addr_reg_1685;
wire   [0:0] tmp_6_i1_fu_1300_p2;
reg   [0:0] tmp_6_i1_reg_1691;
wire   [0:0] tmp_8_i1_fu_1305_p2;
reg   [0:0] tmp_8_i1_reg_1696;
wire   [32:0] tmp_14_fu_1310_p3;
reg   [32:0] tmp_14_reg_1701;
reg   [7:0] line_buffer_addr_2_reg_1706;
reg   [7:0] line_buffer_addr_3_reg_1711;
reg   [7:0] line_buffer_addr_5_reg_1717;
reg   [7:0] line_buffer_load_2_reg_1722;
wire   [0:0] compute_2_fu_1396_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_378;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_idle;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_ready;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_AXI_video_strm_TREADY;
wire   [7:0] grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_din;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_write;
wire   [7:0] grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_din;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_write;
wire   [7:0] grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_din;
wire    grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_write;
reg   [9:0] indvar_flatten_phi_fu_405_p4;
reg   [4:0] row_assign_phi_fu_416_p4;
reg   [4:0] col_assign_phi_fu_427_p4;
reg    ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start;
wire    img_input_data_stream_0_V_full_n;
reg    img_input_data_stream_0_V_write;
wire    img_input_data_stream_1_V_full_n;
reg    img_input_data_stream_1_V_write;
wire    img_input_data_stream_2_V_full_n;
reg    img_input_data_stream_2_V_write;
wire   [63:0] tmp_8_cast_fu_1063_p1;
wire  signed [63:0] tmp_9_cast_fu_1074_p1;
wire   [63:0] tmp_10_cast_fu_1089_p1;
wire  signed [63:0] tmp_12_cast_fu_1099_p1;
wire   [63:0] tmp_13_cast_fu_1109_p1;
wire  signed [63:0] tmp_15_cast_fu_1119_p1;
wire  signed [63:0] tmp_7_cast_fu_1124_p1;
wire  signed [63:0] tmp_11_cast_fu_1133_p1;
wire  signed [63:0] tmp_14_cast_fu_1146_p1;
wire  signed [63:0] tmp_18_cast_fu_1295_p1;
wire   [63:0] tmp_15_fu_1317_p1;
wire  signed [63:0] tmp_19_cast_fu_1327_p1;
wire  signed [63:0] tmp_20_cast_fu_1337_p1;
wire  signed [63:0] tmp_23_cast_fu_1347_p1;
wire   [63:0] tmp_20_fu_1357_p3;
reg   [7:0] output_conv_1_0_1_fu_186;
reg   [7:0] output_conv_1_1_1_fu_190;
reg   [31:0] row_c2_1_fu_194;
wire   [31:0] grp_fu_1268_p2;
reg    ap_sig_cseq_ST_pp0_stg34_fsm_36;
reg    ap_sig_490;
reg   [7:0] v_fu_198;
wire   [7:0] tmp_43_1_i_fu_1423_p2;
reg   [31:0] col_c2_1_fu_202;
wire   [5:0] grp_fu_811_p2;
reg    ap_reg_ioackin_OUTPUT_STREAM_TREADY;
reg    ap_sig_cseq_ST_pp0_stg6_fsm_8;
reg    ap_sig_550;
wire   [0:0] tmp_5_i_fu_484_p2;
wire   [0:0] tmp_i_fu_478_p2;
wire   [0:0] exitcond4_fu_514_p2;
wire   [4:0] row_fu_508_p2;
wire   [0:0] tmp_5_i_mid1_fu_534_p2;
wire   [0:0] tmp_i_mid1_fu_528_p2;
wire   [0:0] tmp3_mid1_fu_540_p2;
wire   [0:0] tmp3_fu_490_p2;
wire   [0:0] tmp_6_i_fu_562_p2;
wire   [0:0] tmp_8_i_fu_568_p2;
wire   [0:0] tmp3_mid2_fu_546_p3;
wire   [0:0] tmp2_fu_574_p2;
wire   [0:0] tmp_27_fu_592_p2;
wire   [0:0] tmp_26_fu_586_p2;
wire   [0:0] tmp_29_fu_604_p2;
wire   [0:0] tmp_28_fu_598_p2;
wire   [0:0] tmp_31_fu_616_p2;
wire   [0:0] tmp_30_fu_610_p2;
wire   [0:0] tmp_33_fu_628_p2;
wire   [0:0] tmp_32_fu_622_p2;
wire   [0:0] tmp_35_fu_640_p2;
wire   [0:0] tmp_34_fu_634_p2;
wire   [0:0] tmp_37_fu_652_p2;
wire   [0:0] tmp_36_fu_646_p2;
wire   [0:0] tmp_39_fu_664_p2;
wire   [0:0] tmp_38_fu_658_p2;
wire   [0:0] tmp_41_fu_676_p2;
wire   [0:0] tmp_40_fu_670_p2;
wire   [0:0] tmp_44_fu_694_p2;
wire   [0:0] tmp_43_fu_688_p2;
wire   [0:0] tmp_46_fu_706_p2;
wire   [0:0] tmp_45_fu_700_p2;
wire   [0:0] tmp_48_fu_718_p2;
wire   [0:0] tmp_47_fu_712_p2;
wire   [0:0] tmp_50_fu_730_p2;
wire   [0:0] tmp_49_fu_724_p2;
wire   [0:0] tmp_52_fu_742_p2;
wire   [0:0] tmp_51_fu_736_p2;
wire   [0:0] tmp_54_fu_754_p2;
wire   [0:0] tmp_53_fu_748_p2;
wire   [0:0] tmp_56_fu_766_p2;
wire   [0:0] tmp_55_fu_760_p2;
wire   [0:0] tmp_58_fu_778_p2;
wire   [0:0] tmp_57_fu_772_p2;
wire   [0:0] tmp_60_fu_790_p2;
wire   [0:0] tmp_59_fu_784_p2;
wire   [31:0] grp_fu_811_p0;
wire   [5:0] grp_fu_811_p1;
wire   [0:0] tmp_64_fu_823_p2;
wire   [0:0] tmp_63_fu_817_p2;
wire   [0:0] tmp_66_fu_835_p2;
wire   [0:0] tmp_65_fu_829_p2;
wire   [0:0] tmp_68_fu_847_p2;
wire   [0:0] tmp_67_fu_841_p2;
wire   [0:0] tmp_70_fu_859_p2;
wire   [0:0] tmp_69_fu_853_p2;
wire   [0:0] tmp_72_fu_871_p2;
wire   [0:0] tmp_71_fu_865_p2;
wire   [0:0] tmp_74_fu_883_p2;
wire   [0:0] tmp_73_fu_877_p2;
wire   [0:0] tmp_76_fu_895_p2;
wire   [0:0] tmp_75_fu_889_p2;
wire   [0:0] tmp_78_fu_907_p2;
wire   [0:0] tmp_77_fu_901_p2;
wire   [0:0] tmp_81_fu_925_p2;
wire   [0:0] tmp_80_fu_919_p2;
wire   [0:0] tmp_83_fu_937_p2;
wire   [0:0] tmp_82_fu_931_p2;
wire   [0:0] tmp_85_fu_949_p2;
wire   [0:0] tmp_84_fu_943_p2;
wire   [0:0] tmp_87_fu_961_p2;
wire   [0:0] tmp_86_fu_955_p2;
wire   [0:0] tmp_89_fu_973_p2;
wire   [0:0] tmp_88_fu_967_p2;
wire   [0:0] tmp_91_fu_985_p2;
wire   [0:0] tmp_90_fu_979_p2;
wire   [0:0] tmp_93_fu_997_p2;
wire   [0:0] tmp_92_fu_991_p2;
wire   [0:0] tmp_95_fu_1009_p2;
wire   [0:0] tmp_94_fu_1003_p2;
wire   [0:0] tmp_97_fu_1021_p2;
wire   [0:0] tmp_96_fu_1015_p2;
wire   [6:0] tmp_4_fu_1036_p3;
wire   [7:0] p_shl_cast_fu_1043_p1;
wire   [7:0] tmp_i1_cast_fu_1033_p1;
wire   [7:0] tmp_8_fu_1057_p2;
wire   [8:0] tmp_9_fu_1068_p2;
wire   [7:0] tmp_s_fu_1084_p2;
wire   [8:0] tmp_10_fu_1094_p2;
wire   [7:0] tmp_11_fu_1104_p2;
wire   [8:0] tmp_13_fu_1114_p2;
wire   [8:0] tmp_1_fu_1128_p2;
wire   [8:0] tmp_12_fu_1141_p2;
wire   [7:0] tmp_33_0_1_0_i_fu_1151_p2;
wire   [7:0] tmp_33_0_1_2_2_i_fu_1156_p2;
wire   [7:0] tmp_29_0_1_i_fu_1161_p2;
wire   [7:0] tmp_33_1_1_0_i_fu_1167_p2;
wire   [7:0] tmp5_fu_1177_p2;
wire   [7:0] tmp6_fu_1194_p2;
wire   [7:0] tmp_29_1_1_i_fu_1189_p2;
wire   [7:0] tmp_33_2_1_0_i_fu_1205_p2;
wire   [7:0] tmp_33_2_1_2_2_i_fu_1210_p2;
wire   [7:0] tmp_29_2_i_fu_1200_p2;
wire   [7:0] tmp_29_2_1_i_fu_1215_p2;
wire   [5:0] tmp_62_fu_1244_p1;
wire   [31:0] grp_fu_1268_p0;
wire   [5:0] grp_fu_1268_p1;
wire   [7:0] tmp_99_fu_1277_p1;
wire   [8:0] tmp_16_fu_1289_p2;
wire   [8:0] tmp_17_fu_1322_p2;
wire   [8:0] tmp_18_fu_1332_p2;
wire   [8:0] tmp_21_fu_1342_p2;
wire   [32:0] tmp_19_fu_1352_p2;
wire   [0:0] tmp_5_i1_fu_1380_p2;
wire   [0:0] tmp_i2_fu_1374_p2;
wire   [0:0] tmp8_fu_1390_p2;
wire   [0:0] tmp7_fu_1386_p2;
wire   [7:0] tmp9_fu_1402_p2;
wire   [7:0] tmp_100_fu_1412_p2;
wire   [7:0] tmp12_fu_1417_p2;
wire   [7:0] tmp10_fu_1407_p2;
reg    grp_fu_811_ce;
reg    ap_sig_cseq_ST_pp0_stg9_fsm_11;
reg    ap_sig_1119;
reg    ap_sig_cseq_ST_pp0_stg10_fsm_12;
reg    ap_sig_1127;
reg    ap_sig_cseq_ST_pp0_stg11_fsm_13;
reg    ap_sig_1135;
reg    ap_sig_cseq_ST_pp0_stg12_fsm_14;
reg    ap_sig_1143;
reg    ap_sig_cseq_ST_pp0_stg13_fsm_15;
reg    ap_sig_1151;
reg    ap_sig_cseq_ST_pp0_stg14_fsm_16;
reg    ap_sig_1159;
reg    ap_sig_cseq_ST_pp0_stg15_fsm_17;
reg    ap_sig_1167;
reg    ap_sig_cseq_ST_pp0_stg16_fsm_18;
reg    ap_sig_1175;
reg    ap_sig_cseq_ST_pp0_stg17_fsm_19;
reg    ap_sig_1183;
reg    ap_sig_cseq_ST_pp0_stg18_fsm_20;
reg    ap_sig_1191;
reg    ap_sig_cseq_ST_pp0_stg19_fsm_21;
reg    ap_sig_1199;
reg    ap_sig_cseq_ST_pp0_stg20_fsm_22;
reg    ap_sig_1207;
reg    ap_sig_cseq_ST_pp0_stg21_fsm_23;
reg    ap_sig_1214;
reg    ap_sig_cseq_ST_pp0_stg22_fsm_24;
reg    ap_sig_1222;
reg    ap_sig_cseq_ST_pp0_stg23_fsm_25;
reg    ap_sig_1230;
reg    ap_sig_cseq_ST_pp0_stg24_fsm_26;
reg    ap_sig_1237;
reg    ap_sig_cseq_ST_pp0_stg25_fsm_27;
reg    ap_sig_1245;
reg    ap_sig_cseq_ST_pp0_stg26_fsm_28;
reg    ap_sig_1253;
reg    ap_sig_cseq_ST_pp0_stg27_fsm_29;
reg    ap_sig_1261;
reg    ap_sig_cseq_ST_pp0_stg28_fsm_30;
reg    ap_sig_1269;
reg    ap_sig_cseq_ST_pp0_stg29_fsm_31;
reg    ap_sig_1277;
reg    ap_sig_cseq_ST_pp0_stg30_fsm_32;
reg    ap_sig_1285;
reg    ap_sig_cseq_ST_pp0_stg31_fsm_33;
reg    ap_sig_1293;
reg    ap_sig_cseq_ST_pp0_stg32_fsm_34;
reg    ap_sig_1301;
reg    ap_sig_cseq_ST_pp0_stg33_fsm_35;
reg    ap_sig_1309;
reg    grp_fu_1268_ce;
reg    ap_sig_cseq_ST_st76_fsm_38;
reg    ap_sig_1466;
reg   [38:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 39'b1;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start = 1'b0;
#0 ap_reg_ioackin_OUTPUT_STREAM_TREADY = 1'b0;
end

net_line_buffer #(
    .DataWidth( 8 ),
    .AddressRange( 156 ),
    .AddressWidth( 8 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_address0),
    .ce0(line_buffer_ce0),
    .we0(line_buffer_we0),
    .d0(line_buffer_d0),
    .q0(line_buffer_q0),
    .address1(line_buffer_address1),
    .ce1(line_buffer_ce1),
    .we1(line_buffer_we1),
    .d1(line_buffer_d1),
    .q1(line_buffer_q1)
);

net_line_buffer_1 #(
    .DataWidth( 8 ),
    .AddressRange( 252 ),
    .AddressWidth( 8 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_1_address0),
    .ce0(line_buffer_1_ce0),
    .we0(line_buffer_1_we0),
    .d0(line_buffer_1_d0),
    .q0(line_buffer_1_q0),
    .address1(line_buffer_1_address1),
    .ce1(line_buffer_1_ce1),
    .we1(line_buffer_1_we1),
    .d1(line_buffer_1_d1),
    .q1(line_buffer_1_q1)
);

net_AXIvideo2Mat_32_28_28_4096_s grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start),
    .ap_done(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done),
    .ap_idle(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_idle),
    .ap_ready(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_ready),
    .AXI_video_strm_TDATA(INPUT_STREAM_TDATA),
    .AXI_video_strm_TVALID(INPUT_STREAM_TVALID),
    .AXI_video_strm_TREADY(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_AXI_video_strm_TREADY),
    .AXI_video_strm_TKEEP(INPUT_STREAM_TKEEP),
    .AXI_video_strm_TSTRB(INPUT_STREAM_TSTRB),
    .AXI_video_strm_TUSER(INPUT_STREAM_TUSER),
    .AXI_video_strm_TLAST(INPUT_STREAM_TLAST),
    .AXI_video_strm_TID(INPUT_STREAM_TID),
    .AXI_video_strm_TDEST(INPUT_STREAM_TDEST),
    .img_data_stream_0_V_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_input_data_stream_0_V_full_n),
    .img_data_stream_0_V_write(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_input_data_stream_1_V_full_n),
    .img_data_stream_1_V_write(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_input_data_stream_2_V_full_n),
    .img_data_stream_2_V_write(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_write)
);

net_srem_32ns_6ns_6_36 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
net_srem_32ns_6ns_6_36_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_811_p0),
    .din1(grp_fu_811_p1),
    .ce(grp_fu_811_ce),
    .dout(grp_fu_811_p2)
);

net_srem_32ns_6ns_32_36 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
net_srem_32ns_6ns_32_36_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1268_p0),
    .din1(grp_fu_1268_p1),
    .ce(grp_fu_1268_ce),
    .dout(grp_fu_1268_p2)
);

FIFO_net_img_input_data_stream_0_V img_input_data_stream_0_V_img_input_data_stream_0_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_din),
    .if_full_n(img_input_data_stream_0_V_full_n),
    .if_write(img_input_data_stream_0_V_write),
    .if_dout(img_input_data_stream_0_V_dout),
    .if_empty_n(img_input_data_stream_0_V_empty_n),
    .if_read(img_input_data_stream_0_V_read)
);

FIFO_net_img_input_data_stream_1_V img_input_data_stream_1_V_img_input_data_stream_1_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_din),
    .if_full_n(img_input_data_stream_1_V_full_n),
    .if_write(img_input_data_stream_1_V_write),
    .if_dout(img_input_data_stream_1_V_dout),
    .if_empty_n(img_input_data_stream_1_V_empty_n),
    .if_read(img_input_data_stream_1_V_read)
);

FIFO_net_img_input_data_stream_2_V img_input_data_stream_2_V_img_input_data_stream_2_V_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_din),
    .if_full_n(img_input_data_stream_2_V_full_n),
    .if_write(img_input_data_stream_2_V_write),
    .if_dout(img_input_data_stream_2_V_dout),
    .if_empty_n(img_input_data_stream_2_V_empty_n),
    .if_read(img_input_data_stream_2_V_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start <= 1'b1;
        end else if ((1'b1 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_ready)) begin
            ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_OUTPUT_STREAM_TREADY <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b1 == OUTPUT_STREAM_TREADY))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~(1'b0 == exitcond_flatten_fu_496_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) & ~(1'b0 == exitcond_flatten_reg_1499)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
        col_assign_reg_423 <= col_reg_1574;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done))) begin
        col_assign_reg_423 <= ap_const_lv5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) & (1'b0 == tmp_42_reg_1526) & (1'b0 == tmp_61_reg_1530) & (1'b0 == tmp_5_fu_1248_p2))) begin
        col_c2_1_fu_202 <= grp_fu_811_p2;
    end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) & (1'b0 == tmp_42_reg_1526) & (1'b0 == tmp_61_reg_1530) & ~(1'b0 == tmp_5_fu_1248_p2)))) begin
        col_c2_1_fu_202 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
        indvar_flatten_reg_401 <= indvar_flatten_next_reg_1503;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done))) begin
        indvar_flatten_reg_401 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
        row_assign_reg_412 <= row_assign_mid2_reg_1515;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done))) begin
        row_assign_reg_412 <= ap_const_lv5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg34_fsm_36) & (1'b0 == ap_reg_ppstg_tmp_42_reg_1526_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_61_reg_1530_pp0_iter1) & ~(1'b0 == tmp_5_reg_1662))) begin
        row_c2_1_fu_194 <= grp_fu_1268_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        row_c2_1_fu_194 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10)) begin
        ap_reg_ppstg_output_conv_1_0_reg_1649_pp0_iter1 <= output_conv_1_0_reg_1649;
        ap_reg_ppstg_output_conv_1_1_reg_1656_pp0_iter1 <= output_conv_1_1_reg_1656;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
        ap_reg_ppstg_tmp_42_reg_1526_pp0_iter1 <= tmp_42_reg_1526;
        ap_reg_ppstg_tmp_61_reg_1530_pp0_iter1 <= tmp_61_reg_1530;
        ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1 <= tmp_79_reg_1539;
        ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1 <= tmp_98_reg_1543;
        col_c2_1_load_1_reg_1671 <= col_c2_1_fu_202;
        exitcond_flatten_reg_1499 <= exitcond_flatten_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & (1'b0 == exitcond_flatten_fu_496_p2))) begin
        col_assign_mid2_reg_1508 <= col_assign_mid2_fu_520_p3;
        compute_1_reg_1520 <= compute_1_fu_580_p2;
        tmp_42_reg_1526 <= tmp_42_fu_682_p2;
        tmp_79_reg_1539 <= tmp_79_fu_913_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        col_reg_1574 <= col_fu_1079_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37)) begin
        compute_2_reg_1727 <= compute_2_fu_1396_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)))) begin
        indvar_flatten_next_reg_1503 <= indvar_flatten_next_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        line_buffer_1_addr_2_reg_1568 <= tmp_9_cast_fu_1074_p1;
        line_buffer_1_addr_reg_1562 <= tmp_8_cast_fu_1063_p1;
        tmp_7_cast5_reg_1554 <= tmp_7_cast5_fu_1053_p1;
        tmp_7_reg_1547 <= tmp_7_fu_1047_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == exitcond_flatten_reg_1499))) begin
        line_buffer_1_addr_3_reg_1579 <= tmp_10_cast_fu_1089_p1;
        line_buffer_1_addr_5_reg_1584 <= tmp_12_cast_fu_1099_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        line_buffer_1_addr_6_reg_1589 <= tmp_13_cast_fu_1109_p1;
        line_buffer_1_addr_8_reg_1595 <= tmp_15_cast_fu_1119_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        line_buffer_1_load_2_reg_1601 <= line_buffer_1_q0;
        line_buffer_1_load_3_reg_1606 <= line_buffer_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1))) begin
        line_buffer_addr_2_reg_1706[7 : 1] <= tmp_19_cast_fu_1327_p1[7 : 1];
        line_buffer_addr_3_reg_1711[7 : 1] <= tmp_20_cast_fu_1337_p1[7 : 1];
        line_buffer_addr_5_reg_1717[7 : 1] <= tmp_23_cast_fu_1347_p1[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & (1'b0 == tmp_79_reg_1539) & (1'b0 == tmp_98_reg_1543))) begin
        line_buffer_addr_reg_1685[7 : 1] <= tmp_18_cast_fu_1295_p1[7 : 1];
        tmp_17_cast_reg_1678[8 : 1] <= tmp_17_cast_fu_1281_p3[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1))) begin
        line_buffer_load_2_reg_1722 <= line_buffer_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10))) begin
        output_conv_1_0_1_fu_186 <= output_conv_1_0_fu_1221_p3;
        output_conv_1_1_1_fu_190 <= output_conv_1_1_fu_1228_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10))) begin
        output_conv_1_0_reg_1649 <= output_conv_1_0_fu_1221_p3;
        output_conv_1_1_reg_1656 <= output_conv_1_1_fu_1228_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9))) begin
        output_conv_1_1_1_load_reg_1634 <= output_conv_1_1_1_fu_190;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == exitcond_flatten_reg_1499)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        reg_463 <= line_buffer_1_q0;
        reg_468 <= line_buffer_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & (1'b0 == exitcond_flatten_fu_496_p2))) begin
        row_assign_mid2_reg_1515 <= row_assign_mid2_fu_554_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9) & ~(1'b0 == compute_1_reg_1520))) begin
        tmp4_reg_1644 <= tmp4_fu_1181_p2;
        tmp_33_1_1_2_2_i_reg_1639 <= tmp_33_1_1_2_2_i_fu_1172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279))) begin
        tmp_101_reg_1611 <= img_input_data_stream_0_V_dout;
        tmp_102_reg_1618 <= img_input_data_stream_1_V_dout;
        tmp_103_reg_1626 <= img_input_data_stream_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1))) begin
        tmp_14_reg_1701[32 : 1] <= tmp_14_fu_1310_p3[32 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) & (1'b0 == tmp_42_reg_1526) & (1'b0 == tmp_61_reg_1530))) begin
        tmp_5_reg_1662 <= tmp_5_fu_1248_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & (1'b0 == exitcond_flatten_fu_496_p2) & (1'b0 == tmp_42_fu_682_p2))) begin
        tmp_61_reg_1530 <= tmp_61_fu_796_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
        tmp_6_i1_reg_1691 <= tmp_6_i1_fu_1300_p2;
        tmp_8_i1_reg_1696 <= tmp_8_i1_fu_1305_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & (1'b0 == exitcond_flatten_fu_496_p2) & (1'b0 == tmp_79_fu_913_p2))) begin
        tmp_98_reg_1543 <= tmp_98_fu_1027_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1) & ~(1'b0 == compute_2_fu_1396_p2))) begin
        v_fu_198 <= tmp_43_1_i_fu_1423_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0))) begin
        OUTPUT_STREAM_TDATA_blk_n = OUTPUT_STREAM_TREADY;
    end else begin
        OUTPUT_STREAM_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY))) begin
        OUTPUT_STREAM_TVALID = 1'b1;
    end else begin
        OUTPUT_STREAM_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st76_fsm_38)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st76_fsm_38)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_117) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1127) begin
        ap_sig_cseq_ST_pp0_stg10_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg10_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1135) begin
        ap_sig_cseq_ST_pp0_stg11_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg11_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1143) begin
        ap_sig_cseq_ST_pp0_stg12_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg12_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1151) begin
        ap_sig_cseq_ST_pp0_stg13_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg13_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1159) begin
        ap_sig_cseq_ST_pp0_stg14_fsm_16 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg14_fsm_16 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1167) begin
        ap_sig_cseq_ST_pp0_stg15_fsm_17 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg15_fsm_17 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1175) begin
        ap_sig_cseq_ST_pp0_stg16_fsm_18 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg16_fsm_18 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1183) begin
        ap_sig_cseq_ST_pp0_stg17_fsm_19 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg17_fsm_19 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1191) begin
        ap_sig_cseq_ST_pp0_stg18_fsm_20 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg18_fsm_20 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1199) begin
        ap_sig_cseq_ST_pp0_stg19_fsm_21 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg19_fsm_21 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_216) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1207) begin
        ap_sig_cseq_ST_pp0_stg20_fsm_22 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg20_fsm_22 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1214) begin
        ap_sig_cseq_ST_pp0_stg21_fsm_23 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg21_fsm_23 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1222) begin
        ap_sig_cseq_ST_pp0_stg22_fsm_24 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg22_fsm_24 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1230) begin
        ap_sig_cseq_ST_pp0_stg23_fsm_25 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg23_fsm_25 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1237) begin
        ap_sig_cseq_ST_pp0_stg24_fsm_26 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg24_fsm_26 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1245) begin
        ap_sig_cseq_ST_pp0_stg25_fsm_27 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg25_fsm_27 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1253) begin
        ap_sig_cseq_ST_pp0_stg26_fsm_28 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg26_fsm_28 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1261) begin
        ap_sig_cseq_ST_pp0_stg27_fsm_29 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg27_fsm_29 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1269) begin
        ap_sig_cseq_ST_pp0_stg28_fsm_30 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg28_fsm_30 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1277) begin
        ap_sig_cseq_ST_pp0_stg29_fsm_31 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg29_fsm_31 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_143) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1285) begin
        ap_sig_cseq_ST_pp0_stg30_fsm_32 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg30_fsm_32 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1293) begin
        ap_sig_cseq_ST_pp0_stg31_fsm_33 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg31_fsm_33 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1301) begin
        ap_sig_cseq_ST_pp0_stg32_fsm_34 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg32_fsm_34 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1309) begin
        ap_sig_cseq_ST_pp0_stg33_fsm_35 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg33_fsm_35 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_490) begin
        ap_sig_cseq_ST_pp0_stg34_fsm_36 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg34_fsm_36 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_329) begin
        ap_sig_cseq_ST_pp0_stg35_fsm_37 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg35_fsm_37 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_241) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_154) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_257) begin
        ap_sig_cseq_ST_pp0_stg5_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg5_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_550) begin
        ap_sig_cseq_ST_pp0_stg6_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg6_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_295) begin
        ap_sig_cseq_ST_pp0_stg7_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg7_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_313) begin
        ap_sig_cseq_ST_pp0_stg8_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg8_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1119) begin
        ap_sig_cseq_ST_pp0_stg9_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg9_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_56) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_378) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1466) begin
        ap_sig_cseq_ST_st76_fsm_38 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st76_fsm_38 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY)) begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY;
    end else begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499))) begin
        col_assign_phi_fu_427_p4 = col_reg_1574;
    end else begin
        col_assign_phi_fu_427_p4 = col_assign_reg_423;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) | (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) | (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) | (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) | ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9) | (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10) | (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) | (1'b1 == ap_sig_cseq_ST_pp0_stg34_fsm_36) | (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8) | (1'b1 == ap_sig_cseq_ST_pp0_stg9_fsm_11) | (1'b1 == ap_sig_cseq_ST_pp0_stg10_fsm_12) | (1'b1 == ap_sig_cseq_ST_pp0_stg11_fsm_13) | (1'b1 == ap_sig_cseq_ST_pp0_stg12_fsm_14) | (1'b1 == ap_sig_cseq_ST_pp0_stg13_fsm_15) | (1'b1 == ap_sig_cseq_ST_pp0_stg14_fsm_16) | (1'b1 == ap_sig_cseq_ST_pp0_stg15_fsm_17) | (1'b1 == ap_sig_cseq_ST_pp0_stg16_fsm_18) | (1'b1 == ap_sig_cseq_ST_pp0_stg17_fsm_19) | (1'b1 == ap_sig_cseq_ST_pp0_stg18_fsm_20) | (1'b1 == ap_sig_cseq_ST_pp0_stg19_fsm_21) | (1'b1 == ap_sig_cseq_ST_pp0_stg20_fsm_22) | (1'b1 == ap_sig_cseq_ST_pp0_stg21_fsm_23) | (1'b1 == ap_sig_cseq_ST_pp0_stg22_fsm_24) | (1'b1 == ap_sig_cseq_ST_pp0_stg23_fsm_25) | (1'b1 == ap_sig_cseq_ST_pp0_stg24_fsm_26) | (1'b1 == ap_sig_cseq_ST_pp0_stg25_fsm_27) | (1'b1 == ap_sig_cseq_ST_pp0_stg26_fsm_28) | (1'b1 == ap_sig_cseq_ST_pp0_stg27_fsm_29) | (1'b1 == ap_sig_cseq_ST_pp0_stg28_fsm_30) | (1'b1 == ap_sig_cseq_ST_pp0_stg29_fsm_31) | (1'b1 == ap_sig_cseq_ST_pp0_stg30_fsm_32) | (1'b1 == ap_sig_cseq_ST_pp0_stg31_fsm_33) | (1'b1 == ap_sig_cseq_ST_pp0_stg32_fsm_34) | (1'b1 == ap_sig_cseq_ST_pp0_stg33_fsm_35))) begin
        grp_fu_1268_ce = 1'b1;
    end else begin
        grp_fu_1268_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) | (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) | (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) | (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) | ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9) | (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10) | (1'b1 == ap_sig_cseq_ST_pp0_stg35_fsm_37) | (1'b1 == ap_sig_cseq_ST_pp0_stg34_fsm_36) | (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8) | (1'b1 == ap_sig_cseq_ST_pp0_stg9_fsm_11) | (1'b1 == ap_sig_cseq_ST_pp0_stg10_fsm_12) | (1'b1 == ap_sig_cseq_ST_pp0_stg11_fsm_13) | (1'b1 == ap_sig_cseq_ST_pp0_stg12_fsm_14) | (1'b1 == ap_sig_cseq_ST_pp0_stg13_fsm_15) | (1'b1 == ap_sig_cseq_ST_pp0_stg14_fsm_16) | (1'b1 == ap_sig_cseq_ST_pp0_stg15_fsm_17) | (1'b1 == ap_sig_cseq_ST_pp0_stg16_fsm_18) | (1'b1 == ap_sig_cseq_ST_pp0_stg17_fsm_19) | (1'b1 == ap_sig_cseq_ST_pp0_stg18_fsm_20) | (1'b1 == ap_sig_cseq_ST_pp0_stg19_fsm_21) | (1'b1 == ap_sig_cseq_ST_pp0_stg20_fsm_22) | (1'b1 == ap_sig_cseq_ST_pp0_stg21_fsm_23) | (1'b1 == ap_sig_cseq_ST_pp0_stg22_fsm_24) | (1'b1 == ap_sig_cseq_ST_pp0_stg23_fsm_25) | (1'b1 == ap_sig_cseq_ST_pp0_stg24_fsm_26) | (1'b1 == ap_sig_cseq_ST_pp0_stg25_fsm_27) | (1'b1 == ap_sig_cseq_ST_pp0_stg26_fsm_28) | (1'b1 == ap_sig_cseq_ST_pp0_stg27_fsm_29) | (1'b1 == ap_sig_cseq_ST_pp0_stg28_fsm_30) | (1'b1 == ap_sig_cseq_ST_pp0_stg29_fsm_31) | (1'b1 == ap_sig_cseq_ST_pp0_stg30_fsm_32) | (1'b1 == ap_sig_cseq_ST_pp0_stg31_fsm_33) | (1'b1 == ap_sig_cseq_ST_pp0_stg32_fsm_34) | (1'b1 == ap_sig_cseq_ST_pp0_stg33_fsm_35))) begin
        grp_fu_811_ce = 1'b1;
    end else begin
        grp_fu_811_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279))) begin
        img_input_data_stream_0_V_read = 1'b1;
    end else begin
        img_input_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        img_input_data_stream_0_V_write = grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_0_V_write;
    end else begin
        img_input_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279))) begin
        img_input_data_stream_1_V_read = 1'b1;
    end else begin
        img_input_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        img_input_data_stream_1_V_write = grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_1_V_write;
    end else begin
        img_input_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279))) begin
        img_input_data_stream_2_V_read = 1'b1;
    end else begin
        img_input_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        img_input_data_stream_2_V_write = grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_img_data_stream_2_V_write;
    end else begin
        img_input_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499))) begin
        indvar_flatten_phi_fu_405_p4 = indvar_flatten_next_reg_1503;
    end else begin
        indvar_flatten_phi_fu_405_p4 = indvar_flatten_reg_401;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10)) begin
            line_buffer_1_address0 = line_buffer_1_addr_8_reg_1595;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) begin
            line_buffer_1_address0 = tmp_14_cast_fu_1146_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) begin
            line_buffer_1_address0 = line_buffer_1_addr_3_reg_1579;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7)) begin
            line_buffer_1_address0 = line_buffer_1_addr_2_reg_1568;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            line_buffer_1_address0 = tmp_7_cast_fu_1124_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            line_buffer_1_address0 = tmp_13_cast_fu_1109_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            line_buffer_1_address0 = tmp_10_cast_fu_1089_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            line_buffer_1_address0 = tmp_8_cast_fu_1063_p1;
        end else begin
            line_buffer_1_address0 = 'bx;
        end
    end else begin
        line_buffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) begin
            line_buffer_1_address1 = line_buffer_1_addr_6_reg_1589;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) begin
            line_buffer_1_address1 = line_buffer_1_addr_5_reg_1584;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7)) begin
            line_buffer_1_address1 = tmp_11_cast_fu_1133_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            line_buffer_1_address1 = line_buffer_1_addr_reg_1562;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            line_buffer_1_address1 = tmp_15_cast_fu_1119_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            line_buffer_1_address1 = tmp_12_cast_fu_1099_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            line_buffer_1_address1 = tmp_9_cast_fu_1074_p1;
        end else begin
            line_buffer_1_address1 = 'bx;
        end
    end else begin
        line_buffer_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_1_ce0 = 1'b1;
    end else begin
        line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_1_ce1 = 1'b1;
    end else begin
        line_buffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10))) begin
        line_buffer_1_d0 = tmp_103_reg_1626;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8))) begin
        line_buffer_1_d0 = line_buffer_1_load_3_reg_1606;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7))) begin
        line_buffer_1_d0 = img_input_data_stream_0_V_dout;
    end else if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)))) begin
        line_buffer_1_d0 = reg_463;
    end else begin
        line_buffer_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8))) begin
        line_buffer_1_d1 = tmp_102_reg_1618;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7))) begin
        line_buffer_1_d1 = line_buffer_1_load_2_reg_1601;
    end else if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)))) begin
        line_buffer_1_d1 = reg_468;
    end else begin
        line_buffer_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg8_fsm_10)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_1_we0 = 1'b1;
    end else begin
        line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg7_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten_reg_1499) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_1_we1 = 1'b1;
    end else begin
        line_buffer_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it1)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) begin
            line_buffer_address0 = line_buffer_addr_3_reg_1711;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            line_buffer_address0 = line_buffer_addr_2_reg_1706;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            line_buffer_address0 = tmp_15_fu_1317_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            line_buffer_address0 = tmp_19_cast_fu_1327_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) begin
            line_buffer_address0 = tmp_18_cast_fu_1295_p1;
        end else begin
            line_buffer_address0 = 'bx;
        end
    end else begin
        line_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        line_buffer_address1 = tmp_20_fu_1357_p3;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        line_buffer_address1 = line_buffer_addr_reg_1685;
    end else if ((((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7)))) begin
        line_buffer_address1 = line_buffer_addr_5_reg_1717;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4))) begin
        line_buffer_address1 = tmp_20_cast_fu_1337_p1;
    end else begin
        line_buffer_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_ce0 = 1'b1;
    end else begin
        line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_7) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)))) begin
        line_buffer_ce1 = 1'b1;
    end else begin
        line_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it1)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) begin
            line_buffer_d0 = line_buffer_q1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            line_buffer_d0 = output_conv_1_0_reg_1649;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            line_buffer_d0 = line_buffer_q0;
        end else begin
            line_buffer_d0 = 'bx;
        end
    end else begin
        line_buffer_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it1)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)) begin
            line_buffer_d1 = output_conv_1_1_reg_1656;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            line_buffer_d1 = line_buffer_load_2_reg_1722;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            line_buffer_d1 = line_buffer_q0;
        end else begin
            line_buffer_d1 = 'bx;
        end
    end else begin
        line_buffer_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_we0 = 1'b1;
    end else begin
        line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == ap_reg_ppstg_tmp_79_reg_1539_pp0_iter1) & (1'b0 == ap_reg_ppstg_tmp_98_reg_1543_pp0_iter1) & (1'b1 == ap_sig_cseq_ST_pp0_stg6_fsm_8)))) begin
        line_buffer_we1 = 1'b1;
    end else begin
        line_buffer_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_flatten_reg_1499))) begin
        row_assign_phi_fu_416_p4 = row_assign_mid2_reg_1515;
    end else begin
        row_assign_phi_fu_416_p4 = row_assign_reg_412;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_done)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~(1'b0 == exitcond_flatten_fu_496_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_3;
            end else if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it2) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(compute_2_reg_1727 == 1'b0) & (1'b0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY)) & ~(1'b0 == exitcond_flatten_fu_496_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st76_fsm_38;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg1_fsm_3 : begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_4;
        end
        ap_ST_pp0_stg2_fsm_4 : begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_5;
        end
        ap_ST_pp0_stg3_fsm_5 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_6;
        end
        ap_ST_pp0_stg4_fsm_6 : begin
            ap_NS_fsm = ap_ST_pp0_stg5_fsm_7;
        end
        ap_ST_pp0_stg5_fsm_7 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_279)) begin
                ap_NS_fsm = ap_ST_pp0_stg6_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg5_fsm_7;
            end
        end
        ap_ST_pp0_stg6_fsm_8 : begin
            ap_NS_fsm = ap_ST_pp0_stg7_fsm_9;
        end
        ap_ST_pp0_stg7_fsm_9 : begin
            ap_NS_fsm = ap_ST_pp0_stg8_fsm_10;
        end
        ap_ST_pp0_stg8_fsm_10 : begin
            ap_NS_fsm = ap_ST_pp0_stg9_fsm_11;
        end
        ap_ST_pp0_stg9_fsm_11 : begin
            ap_NS_fsm = ap_ST_pp0_stg10_fsm_12;
        end
        ap_ST_pp0_stg10_fsm_12 : begin
            ap_NS_fsm = ap_ST_pp0_stg11_fsm_13;
        end
        ap_ST_pp0_stg11_fsm_13 : begin
            ap_NS_fsm = ap_ST_pp0_stg12_fsm_14;
        end
        ap_ST_pp0_stg12_fsm_14 : begin
            ap_NS_fsm = ap_ST_pp0_stg13_fsm_15;
        end
        ap_ST_pp0_stg13_fsm_15 : begin
            ap_NS_fsm = ap_ST_pp0_stg14_fsm_16;
        end
        ap_ST_pp0_stg14_fsm_16 : begin
            ap_NS_fsm = ap_ST_pp0_stg15_fsm_17;
        end
        ap_ST_pp0_stg15_fsm_17 : begin
            ap_NS_fsm = ap_ST_pp0_stg16_fsm_18;
        end
        ap_ST_pp0_stg16_fsm_18 : begin
            ap_NS_fsm = ap_ST_pp0_stg17_fsm_19;
        end
        ap_ST_pp0_stg17_fsm_19 : begin
            ap_NS_fsm = ap_ST_pp0_stg18_fsm_20;
        end
        ap_ST_pp0_stg18_fsm_20 : begin
            ap_NS_fsm = ap_ST_pp0_stg19_fsm_21;
        end
        ap_ST_pp0_stg19_fsm_21 : begin
            ap_NS_fsm = ap_ST_pp0_stg20_fsm_22;
        end
        ap_ST_pp0_stg20_fsm_22 : begin
            ap_NS_fsm = ap_ST_pp0_stg21_fsm_23;
        end
        ap_ST_pp0_stg21_fsm_23 : begin
            ap_NS_fsm = ap_ST_pp0_stg22_fsm_24;
        end
        ap_ST_pp0_stg22_fsm_24 : begin
            ap_NS_fsm = ap_ST_pp0_stg23_fsm_25;
        end
        ap_ST_pp0_stg23_fsm_25 : begin
            ap_NS_fsm = ap_ST_pp0_stg24_fsm_26;
        end
        ap_ST_pp0_stg24_fsm_26 : begin
            ap_NS_fsm = ap_ST_pp0_stg25_fsm_27;
        end
        ap_ST_pp0_stg25_fsm_27 : begin
            ap_NS_fsm = ap_ST_pp0_stg26_fsm_28;
        end
        ap_ST_pp0_stg26_fsm_28 : begin
            ap_NS_fsm = ap_ST_pp0_stg27_fsm_29;
        end
        ap_ST_pp0_stg27_fsm_29 : begin
            ap_NS_fsm = ap_ST_pp0_stg28_fsm_30;
        end
        ap_ST_pp0_stg28_fsm_30 : begin
            ap_NS_fsm = ap_ST_pp0_stg29_fsm_31;
        end
        ap_ST_pp0_stg29_fsm_31 : begin
            ap_NS_fsm = ap_ST_pp0_stg30_fsm_32;
        end
        ap_ST_pp0_stg30_fsm_32 : begin
            ap_NS_fsm = ap_ST_pp0_stg31_fsm_33;
        end
        ap_ST_pp0_stg31_fsm_33 : begin
            ap_NS_fsm = ap_ST_pp0_stg32_fsm_34;
        end
        ap_ST_pp0_stg32_fsm_34 : begin
            ap_NS_fsm = ap_ST_pp0_stg33_fsm_35;
        end
        ap_ST_pp0_stg33_fsm_35 : begin
            ap_NS_fsm = ap_ST_pp0_stg34_fsm_36;
        end
        ap_ST_pp0_stg34_fsm_36 : begin
            ap_NS_fsm = ap_ST_pp0_stg35_fsm_37;
        end
        ap_ST_pp0_stg35_fsm_37 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
        end
        ap_ST_st76_fsm_38 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign INPUT_STREAM_TREADY = grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_AXI_video_strm_TREADY;

assign OUTPUT_STREAM_TDATA = {{{{{{ap_const_lv8_0}, {v_fu_198}}}, {v_fu_198}}}, {v_fu_198}};

assign OUTPUT_STREAM_TDEST = 1'b0;

assign OUTPUT_STREAM_TID = 1'b0;

assign OUTPUT_STREAM_TKEEP = ap_const_lv4_0;

assign OUTPUT_STREAM_TLAST = 1'b0;

assign OUTPUT_STREAM_TSTRB = ap_const_lv4_0;

assign OUTPUT_STREAM_TUSER = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_1119 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_1127 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_1135 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_1143 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_1151 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

always @ (*) begin
    ap_sig_1159 = (1'b1 == ap_CS_fsm[ap_const_lv32_10]);
end

always @ (*) begin
    ap_sig_1167 = (1'b1 == ap_CS_fsm[ap_const_lv32_11]);
end

always @ (*) begin
    ap_sig_117 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_1175 = (1'b1 == ap_CS_fsm[ap_const_lv32_12]);
end

always @ (*) begin
    ap_sig_1183 = (1'b1 == ap_CS_fsm[ap_const_lv32_13]);
end

always @ (*) begin
    ap_sig_1191 = (1'b1 == ap_CS_fsm[ap_const_lv32_14]);
end

always @ (*) begin
    ap_sig_1199 = (1'b1 == ap_CS_fsm[ap_const_lv32_15]);
end

always @ (*) begin
    ap_sig_1207 = (1'b1 == ap_CS_fsm[ap_const_lv32_16]);
end

always @ (*) begin
    ap_sig_1214 = (1'b1 == ap_CS_fsm[ap_const_lv32_17]);
end

always @ (*) begin
    ap_sig_1222 = (1'b1 == ap_CS_fsm[ap_const_lv32_18]);
end

always @ (*) begin
    ap_sig_1230 = (1'b1 == ap_CS_fsm[ap_const_lv32_19]);
end

always @ (*) begin
    ap_sig_1237 = (1'b1 == ap_CS_fsm[ap_const_lv32_1A]);
end

always @ (*) begin
    ap_sig_1245 = (1'b1 == ap_CS_fsm[ap_const_lv32_1B]);
end

always @ (*) begin
    ap_sig_1253 = (1'b1 == ap_CS_fsm[ap_const_lv32_1C]);
end

always @ (*) begin
    ap_sig_1261 = (1'b1 == ap_CS_fsm[ap_const_lv32_1D]);
end

always @ (*) begin
    ap_sig_1269 = (1'b1 == ap_CS_fsm[ap_const_lv32_1E]);
end

always @ (*) begin
    ap_sig_1277 = (1'b1 == ap_CS_fsm[ap_const_lv32_1F]);
end

always @ (*) begin
    ap_sig_1285 = (1'b1 == ap_CS_fsm[ap_const_lv32_20]);
end

always @ (*) begin
    ap_sig_1293 = (1'b1 == ap_CS_fsm[ap_const_lv32_21]);
end

always @ (*) begin
    ap_sig_1301 = (1'b1 == ap_CS_fsm[ap_const_lv32_22]);
end

always @ (*) begin
    ap_sig_1309 = (1'b1 == ap_CS_fsm[ap_const_lv32_23]);
end

always @ (*) begin
    ap_sig_143 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_1466 = (1'b1 == ap_CS_fsm[ap_const_lv32_26]);
end

always @ (*) begin
    ap_sig_154 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_216 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_241 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_257 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_279 = (((1'b0 == exitcond_flatten_reg_1499) & (img_input_data_stream_0_V_empty_n == 1'b0)) | ((1'b0 == exitcond_flatten_reg_1499) & (img_input_data_stream_1_V_empty_n == 1'b0)) | ((1'b0 == exitcond_flatten_reg_1499) & (img_input_data_stream_2_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_295 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_313 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_329 = (1'b1 == ap_CS_fsm[ap_const_lv32_25]);
end

always @ (*) begin
    ap_sig_378 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_490 = (1'b1 == ap_CS_fsm[ap_const_lv32_24]);
end

always @ (*) begin
    ap_sig_550 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_56 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

assign col_assign_mid2_fu_520_p3 = ((exitcond4_fu_514_p2[0:0] === 1'b1) ? ap_const_lv5_0 : col_assign_phi_fu_427_p4);

assign col_fu_1079_p2 = (col_assign_mid2_reg_1508 + ap_const_lv5_1);

assign compute_1_fu_580_p2 = (tmp3_mid2_fu_546_p3 & tmp2_fu_574_p2);

assign compute_2_fu_1396_p2 = (tmp8_fu_1390_p2 & tmp7_fu_1386_p2);

assign exitcond4_fu_514_p2 = ((col_assign_phi_fu_427_p4 == ap_const_lv5_1C) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_496_p2 = ((indvar_flatten_phi_fu_405_p4 == ap_const_lv10_310) ? 1'b1 : 1'b0);

assign grp_fu_1268_p0 = (row_c2_1_fu_194 + ap_const_lv32_1);

assign grp_fu_1268_p1 = ap_const_lv32_1A;

assign grp_fu_811_p0 = (ap_const_lv32_1 + col_c2_1_fu_202);

assign grp_fu_811_p1 = ap_const_lv32_1A;

assign grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start = ap_reg_grp_net_AXIvideo2Mat_32_28_28_4096_s_fu_434_ap_start;

assign indvar_flatten_next_fu_502_p2 = (indvar_flatten_phi_fu_405_p4 + ap_const_lv10_1);

assign output_conv_1_0_fu_1221_p3 = ((compute_1_reg_1520[0:0] === 1'b1) ? tmp_29_2_i_fu_1200_p2 : output_conv_1_0_1_fu_186);

assign output_conv_1_1_fu_1228_p3 = ((compute_1_reg_1520[0:0] === 1'b1) ? tmp_29_2_1_i_fu_1215_p2 : output_conv_1_1_1_load_reg_1634);

assign p_shl_cast_fu_1043_p1 = tmp_4_fu_1036_p3;

assign row_assign_mid2_fu_554_p3 = ((exitcond4_fu_514_p2[0:0] === 1'b1) ? row_fu_508_p2 : row_assign_phi_fu_416_p4);

assign row_fu_508_p2 = (row_assign_phi_fu_416_p4 + ap_const_lv5_1);

assign tmp10_fu_1407_p2 = (tmp9_fu_1402_p2 + ap_reg_ppstg_output_conv_1_0_reg_1649_pp0_iter1);

assign tmp12_fu_1417_p2 = (ap_const_lv8_28 + tmp_100_fu_1412_p2);

assign tmp2_fu_574_p2 = (tmp_6_i_fu_562_p2 & tmp_8_i_fu_568_p2);

assign tmp3_fu_490_p2 = (tmp_5_i_fu_484_p2 & tmp_i_fu_478_p2);

assign tmp3_mid1_fu_540_p2 = (tmp_5_i_mid1_fu_534_p2 & tmp_i_mid1_fu_528_p2);

assign tmp3_mid2_fu_546_p3 = ((exitcond4_fu_514_p2[0:0] === 1'b1) ? tmp3_mid1_fu_540_p2 : tmp3_fu_490_p2);

assign tmp4_fu_1181_p2 = (tmp_101_reg_1611 + tmp5_fu_1177_p2);

assign tmp5_fu_1177_p2 = (tmp_103_reg_1626 + tmp_102_reg_1618);

assign tmp6_fu_1194_p2 = (output_conv_1_0_1_fu_186 + ap_const_lv8_1E);

assign tmp7_fu_1386_p2 = (tmp_6_i1_reg_1691 & tmp_8_i1_reg_1696);

assign tmp8_fu_1390_p2 = (tmp_5_i1_fu_1380_p2 & tmp_i2_fu_1374_p2);

assign tmp9_fu_1402_p2 = (v_fu_198 + ap_reg_ppstg_output_conv_1_0_reg_1649_pp0_iter1);

assign tmp_100_fu_1412_p2 = ap_reg_ppstg_output_conv_1_1_reg_1656_pp0_iter1 << ap_const_lv8_1;

assign tmp_10_cast_fu_1089_p1 = tmp_s_fu_1084_p2;

assign tmp_10_fu_1094_p2 = ($signed(tmp_7_cast5_reg_1554) + $signed(ap_const_lv9_A9));

assign tmp_11_cast_fu_1133_p1 = $signed(tmp_1_fu_1128_p2);

assign tmp_11_fu_1104_p2 = (tmp_7_reg_1547 + ap_const_lv8_56);

assign tmp_12_cast_fu_1099_p1 = $signed(tmp_10_fu_1094_p2);

assign tmp_12_fu_1141_p2 = ($signed(tmp_7_cast5_reg_1554) + $signed(ap_const_lv9_2));

assign tmp_13_cast_fu_1109_p1 = tmp_11_fu_1104_p2;

assign tmp_13_fu_1114_p2 = ($signed(tmp_7_cast5_reg_1554) + $signed(ap_const_lv9_AA));

assign tmp_14_cast_fu_1146_p1 = $signed(tmp_12_fu_1141_p2);

assign tmp_14_fu_1310_p3 = {{col_c2_1_load_1_reg_1671}, {1'b0}};

assign tmp_15_cast_fu_1119_p1 = $signed(tmp_13_fu_1114_p2);

assign tmp_15_fu_1317_p1 = tmp_14_fu_1310_p3;

assign tmp_16_fu_1289_p2 = (ap_const_lv9_34 + tmp_17_cast_fu_1281_p3);

assign tmp_17_cast_fu_1281_p3 = {{tmp_99_fu_1277_p1}, {1'b0}};

assign tmp_17_fu_1322_p2 = (ap_const_lv9_68 + tmp_17_cast_reg_1678);

assign tmp_18_cast_fu_1295_p1 = $signed(tmp_16_fu_1289_p2);

assign tmp_18_fu_1332_p2 = (ap_const_lv9_35 + tmp_17_cast_reg_1678);

assign tmp_19_cast_fu_1327_p1 = $signed(tmp_17_fu_1322_p2);

assign tmp_19_fu_1352_p2 = (tmp_14_reg_1701 | ap_const_lv33_1);

assign tmp_1_fu_1128_p2 = ($signed(tmp_7_cast5_reg_1554) + $signed(ap_const_lv9_1));

assign tmp_20_cast_fu_1337_p1 = $signed(tmp_18_fu_1332_p2);

assign tmp_20_fu_1357_p3 = {{ap_const_lv31_0}, {tmp_19_fu_1352_p2}};

assign tmp_21_fu_1342_p2 = (ap_const_lv9_69 + tmp_17_cast_reg_1678);

assign tmp_23_cast_fu_1347_p1 = $signed(tmp_21_fu_1342_p2);

assign tmp_26_fu_586_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1F) ? 1'b1 : 1'b0);

assign tmp_27_fu_592_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1E) ? 1'b1 : 1'b0);

assign tmp_28_fu_598_p2 = (tmp_27_fu_592_p2 | tmp_26_fu_586_p2);

assign tmp_29_0_1_i_fu_1161_p2 = ($signed(tmp_33_0_1_2_2_i_fu_1156_p2) + $signed(ap_const_lv8_FB));

assign tmp_29_1_1_i_fu_1189_p2 = ($signed(tmp_33_1_1_2_2_i_reg_1639) + $signed(ap_const_lv8_FB));

assign tmp_29_2_1_i_fu_1215_p2 = ($signed(tmp_33_2_1_2_2_i_fu_1210_p2) + $signed(ap_const_lv8_FB));

assign tmp_29_2_i_fu_1200_p2 = (tmp4_reg_1644 + tmp6_fu_1194_p2);

assign tmp_29_fu_604_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1D) ? 1'b1 : 1'b0);

assign tmp_30_fu_610_p2 = (tmp_29_fu_604_p2 | tmp_28_fu_598_p2);

assign tmp_31_fu_616_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1B) ? 1'b1 : 1'b0);

assign tmp_32_fu_622_p2 = (tmp_31_fu_616_p2 | tmp_30_fu_610_p2);

assign tmp_33_0_1_0_i_fu_1151_p2 = (output_conv_1_1_1_fu_190 - tmp_101_reg_1611);

assign tmp_33_0_1_2_2_i_fu_1156_p2 = (tmp_33_0_1_0_i_fu_1151_p2 - tmp_101_reg_1611);

assign tmp_33_1_1_0_i_fu_1167_p2 = (tmp_29_0_1_i_fu_1161_p2 - tmp_102_reg_1618);

assign tmp_33_1_1_2_2_i_fu_1172_p2 = (tmp_33_1_1_0_i_fu_1167_p2 - tmp_102_reg_1618);

assign tmp_33_2_1_0_i_fu_1205_p2 = (tmp_29_1_1_i_fu_1189_p2 - tmp_103_reg_1626);

assign tmp_33_2_1_2_2_i_fu_1210_p2 = (tmp_33_2_1_0_i_fu_1205_p2 - tmp_103_reg_1626);

assign tmp_33_fu_628_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1A) ? 1'b1 : 1'b0);

assign tmp_34_fu_634_p2 = (tmp_33_fu_628_p2 | tmp_32_fu_622_p2);

assign tmp_35_fu_640_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_36_fu_646_p2 = (tmp_35_fu_640_p2 | tmp_34_fu_634_p2);

assign tmp_37_fu_652_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_38_fu_658_p2 = (tmp_37_fu_652_p2 | tmp_36_fu_646_p2);

assign tmp_39_fu_664_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1) ? 1'b1 : 1'b0);

assign tmp_40_fu_670_p2 = (tmp_39_fu_664_p2 | tmp_38_fu_658_p2);

assign tmp_41_fu_676_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_0) ? 1'b1 : 1'b0);

assign tmp_42_fu_682_p2 = (tmp_41_fu_676_p2 | tmp_40_fu_670_p2);

assign tmp_43_1_i_fu_1423_p2 = (tmp12_fu_1417_p2 + tmp10_fu_1407_p2);

assign tmp_43_fu_688_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1F) ? 1'b1 : 1'b0);

assign tmp_44_fu_694_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1E) ? 1'b1 : 1'b0);

assign tmp_45_fu_700_p2 = (tmp_44_fu_694_p2 | tmp_43_fu_688_p2);

assign tmp_46_fu_706_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1D) ? 1'b1 : 1'b0);

assign tmp_47_fu_712_p2 = (tmp_46_fu_706_p2 | tmp_45_fu_700_p2);

assign tmp_48_fu_718_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1C) ? 1'b1 : 1'b0);

assign tmp_49_fu_724_p2 = (tmp_48_fu_718_p2 | tmp_47_fu_712_p2);

assign tmp_4_fu_1036_p3 = {{col_assign_mid2_reg_1508}, {ap_const_lv2_0}};

assign tmp_50_fu_730_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1B) ? 1'b1 : 1'b0);

assign tmp_51_fu_736_p2 = (tmp_50_fu_730_p2 | tmp_49_fu_724_p2);

assign tmp_52_fu_742_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1A) ? 1'b1 : 1'b0);

assign tmp_53_fu_748_p2 = (tmp_52_fu_742_p2 | tmp_51_fu_736_p2);

assign tmp_54_fu_754_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_55_fu_760_p2 = (tmp_54_fu_754_p2 | tmp_53_fu_748_p2);

assign tmp_56_fu_766_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_57_fu_772_p2 = (tmp_56_fu_766_p2 | tmp_55_fu_760_p2);

assign tmp_58_fu_778_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1) ? 1'b1 : 1'b0);

assign tmp_59_fu_784_p2 = (tmp_58_fu_778_p2 | tmp_57_fu_772_p2);

assign tmp_5_fu_1248_p2 = ((tmp_62_fu_1244_p1 == ap_const_lv6_0) ? 1'b1 : 1'b0);

assign tmp_5_i1_fu_1380_p2 = (($signed(row_c2_1_fu_194) < $signed(32'b10111)) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_484_p2 = ((row_assign_phi_fu_416_p4 < ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_5_i_mid1_fu_534_p2 = ((row_fu_508_p2 < ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_60_fu_790_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_0) ? 1'b1 : 1'b0);

assign tmp_61_fu_796_p2 = (tmp_60_fu_790_p2 | tmp_59_fu_784_p2);

assign tmp_62_fu_1244_p1 = grp_fu_811_p2[5:0];

assign tmp_63_fu_817_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1F) ? 1'b1 : 1'b0);

assign tmp_64_fu_823_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1E) ? 1'b1 : 1'b0);

assign tmp_65_fu_829_p2 = (tmp_64_fu_823_p2 | tmp_63_fu_817_p2);

assign tmp_66_fu_835_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1D) ? 1'b1 : 1'b0);

assign tmp_67_fu_841_p2 = (tmp_66_fu_835_p2 | tmp_65_fu_829_p2);

assign tmp_68_fu_847_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1B) ? 1'b1 : 1'b0);

assign tmp_69_fu_853_p2 = (tmp_68_fu_847_p2 | tmp_67_fu_841_p2);

assign tmp_6_i1_fu_1300_p2 = (($signed(col_c2_1_load_1_reg_1671) > $signed(32'b10)) ? 1'b1 : 1'b0);

assign tmp_6_i_fu_562_p2 = ((col_assign_mid2_fu_520_p3 > ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_70_fu_859_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1A) ? 1'b1 : 1'b0);

assign tmp_71_fu_865_p2 = (tmp_70_fu_859_p2 | tmp_69_fu_853_p2);

assign tmp_72_fu_871_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_73_fu_877_p2 = (tmp_72_fu_871_p2 | tmp_71_fu_865_p2);

assign tmp_74_fu_883_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_75_fu_889_p2 = (tmp_74_fu_883_p2 | tmp_73_fu_877_p2);

assign tmp_76_fu_895_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_1) ? 1'b1 : 1'b0);

assign tmp_77_fu_901_p2 = (tmp_76_fu_895_p2 | tmp_75_fu_889_p2);

assign tmp_78_fu_907_p2 = ((col_assign_mid2_fu_520_p3 == ap_const_lv5_0) ? 1'b1 : 1'b0);

assign tmp_79_fu_913_p2 = (tmp_78_fu_907_p2 | tmp_77_fu_901_p2);

assign tmp_7_cast5_fu_1053_p1 = $signed(tmp_7_fu_1047_p2);

assign tmp_7_cast_fu_1124_p1 = $signed(tmp_7_reg_1547);

assign tmp_7_fu_1047_p2 = (p_shl_cast_fu_1043_p1 - tmp_i1_cast_fu_1033_p1);

assign tmp_80_fu_919_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1F) ? 1'b1 : 1'b0);

assign tmp_81_fu_925_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1E) ? 1'b1 : 1'b0);

assign tmp_82_fu_931_p2 = (tmp_81_fu_925_p2 | tmp_80_fu_919_p2);

assign tmp_83_fu_937_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1D) ? 1'b1 : 1'b0);

assign tmp_84_fu_943_p2 = (tmp_83_fu_937_p2 | tmp_82_fu_931_p2);

assign tmp_85_fu_949_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1C) ? 1'b1 : 1'b0);

assign tmp_86_fu_955_p2 = (tmp_85_fu_949_p2 | tmp_84_fu_943_p2);

assign tmp_87_fu_961_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1B) ? 1'b1 : 1'b0);

assign tmp_88_fu_967_p2 = (tmp_87_fu_961_p2 | tmp_86_fu_955_p2);

assign tmp_89_fu_973_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1A) ? 1'b1 : 1'b0);

assign tmp_8_cast_fu_1063_p1 = tmp_8_fu_1057_p2;

assign tmp_8_fu_1057_p2 = (tmp_7_fu_1047_p2 + ap_const_lv8_54);

assign tmp_8_i1_fu_1305_p2 = (($signed(col_c2_1_load_1_reg_1671) < $signed(32'b10111)) ? 1'b1 : 1'b0);

assign tmp_8_i_fu_568_p2 = ((col_assign_mid2_fu_520_p3 < ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_90_fu_979_p2 = (tmp_89_fu_973_p2 | tmp_88_fu_967_p2);

assign tmp_91_fu_985_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_92_fu_991_p2 = (tmp_91_fu_985_p2 | tmp_90_fu_979_p2);

assign tmp_93_fu_997_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_94_fu_1003_p2 = (tmp_93_fu_997_p2 | tmp_92_fu_991_p2);

assign tmp_95_fu_1009_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_1) ? 1'b1 : 1'b0);

assign tmp_96_fu_1015_p2 = (tmp_95_fu_1009_p2 | tmp_94_fu_1003_p2);

assign tmp_97_fu_1021_p2 = ((row_assign_mid2_fu_554_p3 == ap_const_lv5_0) ? 1'b1 : 1'b0);

assign tmp_98_fu_1027_p2 = (tmp_97_fu_1021_p2 | tmp_96_fu_1015_p2);

assign tmp_99_fu_1277_p1 = col_c2_1_fu_202[7:0];

assign tmp_9_cast_fu_1074_p1 = $signed(tmp_9_fu_1068_p2);

assign tmp_9_fu_1068_p2 = ($signed(tmp_7_cast5_fu_1053_p1) + $signed(ap_const_lv9_A8));

assign tmp_i1_cast_fu_1033_p1 = col_assign_mid2_reg_1508;

assign tmp_i2_fu_1374_p2 = (($signed(row_c2_1_fu_194) > $signed(32'b10)) ? 1'b1 : 1'b0);

assign tmp_i_fu_478_p2 = ((row_assign_phi_fu_416_p4 > ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_i_mid1_fu_528_p2 = ((row_fu_508_p2 > ap_const_lv5_2) ? 1'b1 : 1'b0);

assign tmp_s_fu_1084_p2 = (tmp_7_reg_1547 + ap_const_lv8_55);

always @ (posedge ap_clk) begin
    tmp_17_cast_reg_1678[0] <= 1'b0;
    line_buffer_addr_reg_1685[0] <= 1'b0;
    tmp_14_reg_1701[0] <= 1'b0;
    line_buffer_addr_2_reg_1706[0] <= 1'b0;
    line_buffer_addr_3_reg_1711[0] <= 1'b1;
    line_buffer_addr_5_reg_1717[0] <= 1'b1;
end

endmodule //net
