// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module net_AXIvideo2Mat_32_28_28_4096_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        AXI_video_strm_TDATA,
        AXI_video_strm_TVALID,
        AXI_video_strm_TREADY,
        AXI_video_strm_TKEEP,
        AXI_video_strm_TSTRB,
        AXI_video_strm_TUSER,
        AXI_video_strm_TLAST,
        AXI_video_strm_TID,
        AXI_video_strm_TDEST,
        img_data_stream_0_V_din,
        img_data_stream_0_V_full_n,
        img_data_stream_0_V_write,
        img_data_stream_1_V_din,
        img_data_stream_1_V_full_n,
        img_data_stream_1_V_write,
        img_data_stream_2_V_din,
        img_data_stream_2_V_full_n,
        img_data_stream_2_V_write
);

parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv5_1C = 5'b11100;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] AXI_video_strm_TDATA;
input   AXI_video_strm_TVALID;
output   AXI_video_strm_TREADY;
input  [3:0] AXI_video_strm_TKEEP;
input  [3:0] AXI_video_strm_TSTRB;
input  [0:0] AXI_video_strm_TUSER;
input  [0:0] AXI_video_strm_TLAST;
input  [0:0] AXI_video_strm_TID;
input  [0:0] AXI_video_strm_TDEST;
output  [7:0] img_data_stream_0_V_din;
input   img_data_stream_0_V_full_n;
output   img_data_stream_0_V_write;
output  [7:0] img_data_stream_1_V_din;
input   img_data_stream_1_V_full_n;
output   img_data_stream_1_V_write;
output  [7:0] img_data_stream_2_V_din;
input   img_data_stream_2_V_full_n;
output   img_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg AXI_video_strm_TREADY;
reg img_data_stream_0_V_write;
reg img_data_stream_1_V_write;
reg img_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_24;
reg    AXI_video_strm_TDATA_blk_n;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_56;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_63;
reg    ap_reg_ppiten_pp1_it0;
reg    ap_reg_ppiten_pp1_it1;
wire   [0:0] exitcond3_fu_293_p2;
wire   [0:0] brmerge_fu_308_p2;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_83;
reg    img_data_stream_0_V_blk_n;
reg   [0:0] exitcond3_reg_372;
reg    img_data_stream_1_V_blk_n;
reg    img_data_stream_2_V_blk_n;
reg   [0:0] eol_1_reg_158;
reg   [31:0] axi_data_V_1_reg_169;
reg   [4:0] p_1_reg_180;
reg   [0:0] eol_reg_191;
reg   [0:0] axi_last_V_2_reg_203;
reg   [31:0] p_Val2_s_reg_216;
reg   [31:0] tmp_data_V_reg_343;
reg   [0:0] tmp_last_V_reg_351;
wire   [0:0] exitcond2_fu_281_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_122;
wire   [4:0] i_V_fu_287_p2;
reg   [4:0] i_V_reg_367;
reg    ap_sig_127;
reg    ap_sig_137;
wire   [4:0] j_V_fu_299_p2;
wire   [7:0] tmp_104_fu_314_p1;
reg   [7:0] tmp_104_reg_385;
reg   [7:0] tmp_4_reg_390;
reg   [7:0] tmp_5_reg_395;
reg    ap_sig_155;
reg   [0:0] axi_last_V_3_reg_228;
reg   [0:0] axi_last_V1_reg_127;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_173;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_180;
reg   [31:0] axi_data_V_3_reg_240;
reg   [31:0] axi_data_V1_reg_137;
reg   [4:0] p_s_reg_147;
reg   [0:0] eol_1_phi_fu_161_p4;
reg   [31:0] axi_data_V_1_phi_fu_172_p4;
reg   [0:0] eol_phi_fu_195_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0;
wire   [31:0] ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
reg   [31:0] p_Val2_s_phi_fu_220_p4;
reg   [0:0] eol_2_reg_252;
reg   [0:0] sof_1_fu_84;
wire   [0:0] tmp_user_V_fu_272_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_76;
reg    ap_sig_200;
reg    ap_sig_145;
reg    ap_sig_215;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'b1;
#0 ap_reg_ppiten_pp1_it0 = 1'b0;
#0 ap_reg_ppiten_pp1_it1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
            ap_reg_ppiten_pp1_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2))) begin
            ap_reg_ppiten_pp1_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond3_fu_293_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
            ap_reg_ppiten_pp1_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2)) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0)))) begin
            ap_reg_ppiten_pp1_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_reg_137 <= tmp_data_V_reg_343;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_reg_137 <= axi_data_V_3_reg_240;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        axi_data_V_1_reg_169 <= p_Val2_s_reg_216;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2))) begin
        axi_data_V_1_reg_169 <= axi_data_V1_reg_137;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
        axi_data_V_3_reg_240 <= axi_data_V_1_phi_fu_172_p4;
    end else if (((1'b1 == ap_sig_cseq_ST_st7_fsm_5) & (1'b0 == eol_2_reg_252) & ~ap_sig_155)) begin
        axi_data_V_3_reg_240 <= AXI_video_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_reg_127 <= tmp_last_V_reg_351;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_reg_127 <= axi_last_V_3_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_145) begin
        if (ap_sig_200) begin
            axi_last_V_2_reg_203 <= eol_1_phi_fu_161_p4;
        end else if (ap_sig_76) begin
            axi_last_V_2_reg_203 <= AXI_video_strm_TLAST;
        end else if ((1'b1 == 1'b1)) begin
            axi_last_V_2_reg_203 <= ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
        axi_last_V_3_reg_228 <= eol_1_phi_fu_161_p4;
    end else if (((1'b1 == ap_sig_cseq_ST_st7_fsm_5) & (1'b0 == eol_2_reg_252) & ~ap_sig_155)) begin
        axi_last_V_3_reg_228 <= AXI_video_strm_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        eol_1_reg_158 <= axi_last_V_2_reg_203;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2))) begin
        eol_1_reg_158 <= axi_last_V1_reg_127;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
        eol_2_reg_252 <= eol_phi_fu_195_p4;
    end else if (((1'b1 == ap_sig_cseq_ST_st7_fsm_5) & (1'b0 == eol_2_reg_252) & ~ap_sig_155)) begin
        eol_2_reg_252 <= AXI_video_strm_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        eol_reg_191 <= axi_last_V_2_reg_203;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2))) begin
        eol_reg_191 <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & (exitcond3_fu_293_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        p_1_reg_180 <= j_V_fu_299_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b0 == exitcond2_fu_281_p2))) begin
        p_1_reg_180 <= ap_const_lv5_0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_145) begin
        if (ap_sig_200) begin
            p_Val2_s_reg_216 <= axi_data_V_1_phi_fu_172_p4;
        end else if (ap_sig_76) begin
            p_Val2_s_reg_216 <= AXI_video_strm_TDATA;
        end else if ((1'b1 == 1'b1)) begin
            p_Val2_s_reg_216 <= ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_s_reg_147 <= ap_const_lv5_0;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        p_s_reg_147 <= i_V_reg_367;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & (exitcond3_fu_293_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        sof_1_fu_84 <= 1'b0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_fu_84 <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        exitcond3_reg_372 <= exitcond3_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_V_reg_367 <= i_V_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond3_fu_293_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        tmp_104_reg_385 <= tmp_104_fu_314_p1;
        tmp_4_reg_390 <= {{p_Val2_s_phi_fu_220_p4[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_5_reg_395 <= {{p_Val2_s_phi_fu_220_p4[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(AXI_video_strm_TVALID == 1'b0))) begin
        tmp_data_V_reg_343 <= AXI_video_strm_TDATA;
        tmp_last_V_reg_351 <= AXI_video_strm_TLAST;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & (exitcond3_fu_293_p2 == 1'b0) & (1'b0 == brmerge_fu_308_p2)) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_5) & (1'b0 == eol_2_reg_252)))) begin
        AXI_video_strm_TDATA_blk_n = AXI_video_strm_TVALID;
    end else begin
        AXI_video_strm_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(AXI_video_strm_TVALID == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_5) & (1'b0 == eol_2_reg_252) & ~ap_sig_155) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & (exitcond3_fu_293_p2 == 1'b0) & (1'b0 == brmerge_fu_308_p2) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137))))) begin
        AXI_video_strm_TREADY = 1'b1;
    end else begin
        AXI_video_strm_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(1'b0 == exitcond2_fu_281_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & ~(1'b0 == exitcond2_fu_281_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_63) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_24) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_56) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_180) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_122) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_83) begin
        ap_sig_cseq_ST_st7_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_173) begin
        ap_sig_cseq_ST_st8_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        axi_data_V_1_phi_fu_172_p4 = p_Val2_s_reg_216;
    end else begin
        axi_data_V_1_phi_fu_172_p4 = axi_data_V_1_reg_169;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        eol_1_phi_fu_161_p4 = axi_last_V_2_reg_203;
    end else begin
        eol_1_phi_fu_161_p4 = eol_1_reg_158;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        eol_phi_fu_195_p4 = axi_last_V_2_reg_203;
    end else begin
        eol_phi_fu_195_p4 = eol_reg_191;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        img_data_stream_0_V_blk_n = img_data_stream_0_V_full_n;
    end else begin
        img_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        img_data_stream_0_V_write = 1'b1;
    end else begin
        img_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        img_data_stream_1_V_blk_n = img_data_stream_1_V_full_n;
    end else begin
        img_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        img_data_stream_1_V_write = 1'b1;
    end else begin
        img_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372))) begin
        img_data_stream_2_V_blk_n = img_data_stream_2_V_full_n;
    end else begin
        img_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond3_reg_372) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)))) begin
        img_data_stream_2_V_write = 1'b1;
    end else begin
        img_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_215) begin
        if (~(1'b0 == brmerge_fu_308_p2)) begin
            p_Val2_s_phi_fu_220_p4 = axi_data_V_1_phi_fu_172_p4;
        end else if ((1'b0 == brmerge_fu_308_p2)) begin
            p_Val2_s_phi_fu_220_p4 = AXI_video_strm_TDATA;
        end else begin
            p_Val2_s_phi_fu_220_p4 = ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
        end
    end else begin
        p_Val2_s_phi_fu_220_p4 = ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((~(AXI_video_strm_TVALID == 1'b0) & (1'b0 == tmp_user_V_fu_272_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(AXI_video_strm_TVALID == 1'b0) & ~(1'b0 == tmp_user_V_fu_272_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            if (~(1'b0 == exitcond2_fu_281_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : begin
            if (~((1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)) & ~(exitcond3_fu_293_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : begin
            if (((1'b0 == eol_2_reg_252) & ~ap_sig_155)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_155 & ~(1'b0 == eol_2_reg_252))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0 = 'bx;

assign ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0 = 'bx;

always @ (*) begin
    ap_sig_122 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_127 = ((exitcond3_fu_293_p2 == 1'b0) & (1'b0 == brmerge_fu_308_p2) & (AXI_video_strm_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_137 = (((1'b0 == exitcond3_reg_372) & (img_data_stream_0_V_full_n == 1'b0)) | ((1'b0 == exitcond3_reg_372) & (img_data_stream_1_V_full_n == 1'b0)) | ((1'b0 == exitcond3_reg_372) & (img_data_stream_2_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_sig_145 = ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it0) & ap_sig_127) | ((1'b1 == ap_reg_ppiten_pp1_it1) & ap_sig_137)));
end

always @ (*) begin
    ap_sig_155 = ((1'b0 == eol_2_reg_252) & (AXI_video_strm_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_173 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_180 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_200 = ((exitcond3_fu_293_p2 == 1'b0) & ~(1'b0 == brmerge_fu_308_p2));
end

always @ (*) begin
    ap_sig_215 = ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (1'b1 == ap_reg_ppiten_pp1_it0) & (exitcond3_fu_293_p2 == 1'b0));
end

always @ (*) begin
    ap_sig_24 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_56 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_63 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_76 = ((exitcond3_fu_293_p2 == 1'b0) & (1'b0 == brmerge_fu_308_p2));
end

always @ (*) begin
    ap_sig_83 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

assign brmerge_fu_308_p2 = (sof_1_fu_84 | eol_phi_fu_195_p4);

assign exitcond2_fu_281_p2 = ((p_s_reg_147 == ap_const_lv5_1C) ? 1'b1 : 1'b0);

assign exitcond3_fu_293_p2 = ((p_1_reg_180 == ap_const_lv5_1C) ? 1'b1 : 1'b0);

assign i_V_fu_287_p2 = (p_s_reg_147 + ap_const_lv5_1);

assign img_data_stream_0_V_din = tmp_104_reg_385;

assign img_data_stream_1_V_din = tmp_4_reg_390;

assign img_data_stream_2_V_din = tmp_5_reg_395;

assign j_V_fu_299_p2 = (p_1_reg_180 + ap_const_lv5_1);

assign tmp_104_fu_314_p1 = p_Val2_s_phi_fu_220_p4[7:0];

assign tmp_user_V_fu_272_p1 = AXI_video_strm_TUSER;

endmodule //net_AXIvideo2Mat_32_28_28_4096_s
