-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity net_AXIvideo2Mat_32_28_28_4096_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    AXI_video_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    AXI_video_strm_TVALID : IN STD_LOGIC;
    AXI_video_strm_TREADY : OUT STD_LOGIC;
    AXI_video_strm_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    AXI_video_strm_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    AXI_video_strm_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    AXI_video_strm_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    AXI_video_strm_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    AXI_video_strm_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_0_V_full_n : IN STD_LOGIC;
    img_data_stream_0_V_write : OUT STD_LOGIC;
    img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_1_V_full_n : IN STD_LOGIC;
    img_data_stream_1_V_write : OUT STD_LOGIC;
    img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_2_V_full_n : IN STD_LOGIC;
    img_data_stream_2_V_write : OUT STD_LOGIC );
end;


architecture behav of net_AXIvideo2Mat_32_28_28_4096_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_pp1_stg0_fsm_4 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_st7_fsm_5 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_st8_fsm_6 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_true : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_24 : BOOLEAN;
    signal AXI_video_strm_TDATA_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_56 : BOOLEAN;
    signal ap_sig_cseq_ST_pp1_stg0_fsm_4 : STD_LOGIC;
    signal ap_sig_63 : BOOLEAN;
    signal ap_reg_ppiten_pp1_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp1_it1 : STD_LOGIC := '0';
    signal exitcond3_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_5 : STD_LOGIC;
    signal ap_sig_83 : BOOLEAN;
    signal img_data_stream_0_V_blk_n : STD_LOGIC;
    signal exitcond3_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_data_stream_1_V_blk_n : STD_LOGIC;
    signal img_data_stream_2_V_blk_n : STD_LOGIC;
    signal eol_1_reg_158 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_reg_169 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_1_reg_180 : STD_LOGIC_VECTOR (4 downto 0);
    signal eol_reg_191 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_2_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_216 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_343 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_last_V_reg_351 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond2_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_122 : BOOLEAN;
    signal i_V_fu_287_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_V_reg_367 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_127 : BOOLEAN;
    signal ap_sig_137 : BOOLEAN;
    signal j_V_fu_299_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_104_fu_314_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_104_reg_385 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_390 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_395 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_155 : BOOLEAN;
    signal axi_last_V_3_reg_228 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V1_reg_127 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st8_fsm_6 : STD_LOGIC;
    signal ap_sig_173 : BOOLEAN;
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_180 : BOOLEAN;
    signal axi_data_V_3_reg_240 : STD_LOGIC_VECTOR (31 downto 0);
    signal axi_data_V1_reg_137 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_147 : STD_LOGIC_VECTOR (4 downto 0);
    signal eol_1_phi_fu_161_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_phi_fu_172_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal eol_phi_fu_195_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_phi_fu_220_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal eol_2_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_1_fu_84 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_V_fu_272_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_76 : BOOLEAN;
    signal ap_sig_200 : BOOLEAN;
    signal ap_sig_145 : BOOLEAN;
    signal ap_sig_215 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp1_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp1_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V1_reg_137_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                axi_data_V1_reg_137 <= tmp_data_V_reg_343;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                axi_data_V1_reg_137 <= axi_data_V_3_reg_240;
            end if; 
        end if;
    end process;

    axi_data_V_1_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                axi_data_V_1_reg_169 <= p_Val2_s_reg_216;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2))) then 
                axi_data_V_1_reg_169 <= axi_data_V1_reg_137;
            end if; 
        end if;
    end process;

    axi_data_V_3_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0)))) then 
                axi_data_V_3_reg_240 <= axi_data_V_1_phi_fu_172_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_reg_252) and not(ap_sig_155))) then 
                axi_data_V_3_reg_240 <= AXI_video_strm_TDATA;
            end if; 
        end if;
    end process;

    axi_last_V1_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                axi_last_V1_reg_127 <= tmp_last_V_reg_351;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                axi_last_V1_reg_127 <= axi_last_V_3_reg_228;
            end if; 
        end if;
    end process;

    axi_last_V_2_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_145) then
                if (ap_sig_200) then 
                    axi_last_V_2_reg_203 <= eol_1_phi_fu_161_p4;
                elsif (ap_sig_76) then 
                    axi_last_V_2_reg_203 <= AXI_video_strm_TLAST;
                elsif ((ap_true = ap_true)) then 
                    axi_last_V_2_reg_203 <= ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0;
                end if;
            end if; 
        end if;
    end process;

    axi_last_V_3_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0)))) then 
                axi_last_V_3_reg_228 <= eol_1_phi_fu_161_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_reg_252) and not(ap_sig_155))) then 
                axi_last_V_3_reg_228 <= AXI_video_strm_TLAST;
            end if; 
        end if;
    end process;

    eol_1_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                eol_1_reg_158 <= axi_last_V_2_reg_203;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2))) then 
                eol_1_reg_158 <= axi_last_V1_reg_127;
            end if; 
        end if;
    end process;

    eol_2_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0)))) then 
                eol_2_reg_252 <= eol_phi_fu_195_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_reg_252) and not(ap_sig_155))) then 
                eol_2_reg_252 <= AXI_video_strm_TLAST;
            end if; 
        end if;
    end process;

    eol_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                eol_reg_191 <= axi_last_V_2_reg_203;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2))) then 
                eol_reg_191 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    p_1_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                p_1_reg_180 <= j_V_fu_299_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond2_fu_281_p2))) then 
                p_1_reg_180 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_145) then
                if (ap_sig_200) then 
                    p_Val2_s_reg_216 <= axi_data_V_1_phi_fu_172_p4;
                elsif (ap_sig_76) then 
                    p_Val2_s_reg_216 <= AXI_video_strm_TDATA;
                elsif ((ap_true = ap_true)) then 
                    p_Val2_s_reg_216 <= ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
                end if;
            end if; 
        end if;
    end process;

    p_s_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                p_s_reg_147 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                p_s_reg_147 <= i_V_reg_367;
            end if; 
        end if;
    end process;

    sof_1_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
                sof_1_fu_84 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                sof_1_fu_84 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then
                exitcond3_reg_372 <= exitcond3_fu_293_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                i_V_reg_367 <= i_V_fu_287_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then
                tmp_104_reg_385 <= tmp_104_fu_314_p1;
                tmp_4_reg_390 <= p_Val2_s_phi_fu_220_p4(15 downto 8);
                tmp_5_reg_395 <= p_Val2_s_phi_fu_220_p4(23 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((AXI_video_strm_TVALID = ap_const_logic_0)))) then
                tmp_data_V_reg_343 <= AXI_video_strm_TDATA;
                tmp_last_V_reg_351 <= AXI_video_strm_TLAST;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, AXI_video_strm_TVALID, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond3_fu_293_p2, exitcond2_fu_281_p2, ap_sig_127, ap_sig_137, ap_sig_155, eol_2_reg_252, tmp_user_V_fu_272_p1)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((not((AXI_video_strm_TVALID = ap_const_logic_0)) and (ap_const_lv1_0 = tmp_user_V_fu_272_p1))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                elsif ((not((AXI_video_strm_TVALID = ap_const_logic_0)) and not((ap_const_lv1_0 = tmp_user_V_fu_272_p1)))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                if (not((ap_const_lv1_0 = exitcond2_fu_281_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                end if;
            when ap_ST_pp1_stg0_fsm_4 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))) and not((exitcond3_fu_293_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                else
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                end if;
            when ap_ST_st7_fsm_5 => 
                if (((ap_const_lv1_0 = eol_2_reg_252) and not(ap_sig_155))) then
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                elsif ((not(ap_sig_155) and not((ap_const_lv1_0 = eol_2_reg_252)))) then
                    ap_NS_fsm <= ap_ST_st8_fsm_6;
                else
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                end if;
            when ap_ST_st8_fsm_6 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;

    AXI_video_strm_TDATA_blk_n_assign_proc : process(AXI_video_strm_TVALID, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, exitcond3_fu_293_p2, brmerge_fu_308_p2, ap_sig_cseq_ST_st7_fsm_5, eol_2_reg_252)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_fu_308_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_reg_252)))) then 
            AXI_video_strm_TDATA_blk_n <= AXI_video_strm_TVALID;
        else 
            AXI_video_strm_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    AXI_video_strm_TREADY_assign_proc : process(AXI_video_strm_TVALID, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond3_fu_293_p2, brmerge_fu_308_p2, ap_sig_cseq_ST_st7_fsm_5, ap_sig_127, ap_sig_137, ap_sig_155, eol_2_reg_252)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((AXI_video_strm_TVALID = ap_const_logic_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_reg_252) and not(ap_sig_155)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond3_fu_293_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_fu_308_p2) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137)))))) then 
            AXI_video_strm_TREADY <= ap_const_logic_1;
        else 
            AXI_video_strm_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, exitcond2_fu_281_p2, ap_sig_cseq_ST_st4_fsm_3)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = exitcond2_fu_281_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond2_fu_281_p2, ap_sig_cseq_ST_st4_fsm_3)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = exitcond2_fu_281_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0 <= "X";
    ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_sig_122_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_122 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_127_assign_proc : process(AXI_video_strm_TVALID, exitcond3_fu_293_p2, brmerge_fu_308_p2)
    begin
                ap_sig_127 <= ((exitcond3_fu_293_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_fu_308_p2) and (AXI_video_strm_TVALID = ap_const_logic_0));
    end process;


    ap_sig_137_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, exitcond3_reg_372)
    begin
                ap_sig_137 <= (((ap_const_lv1_0 = exitcond3_reg_372) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond3_reg_372) and (img_data_stream_1_V_full_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond3_reg_372) and (img_data_stream_2_V_full_n = ap_const_logic_0)));
    end process;


    ap_sig_145_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, ap_sig_127, ap_sig_137)
    begin
                ap_sig_145 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))));
    end process;


    ap_sig_155_assign_proc : process(AXI_video_strm_TVALID, eol_2_reg_252)
    begin
                ap_sig_155 <= ((ap_const_lv1_0 = eol_2_reg_252) and (AXI_video_strm_TVALID = ap_const_logic_0));
    end process;


    ap_sig_173_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_173 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_180_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_180 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_200_assign_proc : process(exitcond3_fu_293_p2, brmerge_fu_308_p2)
    begin
                ap_sig_200 <= ((exitcond3_fu_293_p2 = ap_const_lv1_0) and not((ap_const_lv1_0 = brmerge_fu_308_p2)));
    end process;


    ap_sig_215_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, exitcond3_fu_293_p2)
    begin
                ap_sig_215 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond3_fu_293_p2 = ap_const_lv1_0));
    end process;


    ap_sig_24_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_24 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_56_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_56 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_63_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_63 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_76_assign_proc : process(exitcond3_fu_293_p2, brmerge_fu_308_p2)
    begin
                ap_sig_76 <= ((exitcond3_fu_293_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_fu_308_p2));
    end process;


    ap_sig_83_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_83 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_cseq_ST_pp1_stg0_fsm_4_assign_proc : process(ap_sig_63)
    begin
        if (ap_sig_63) then 
            ap_sig_cseq_ST_pp1_stg0_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp1_stg0_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_24)
    begin
        if (ap_sig_24) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_56)
    begin
        if (ap_sig_56) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_180)
    begin
        if (ap_sig_180) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_122)
    begin
        if (ap_sig_122) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_5_assign_proc : process(ap_sig_83)
    begin
        if (ap_sig_83) then 
            ap_sig_cseq_ST_st7_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_6_assign_proc : process(ap_sig_173)
    begin
        if (ap_sig_173) then 
            ap_sig_cseq_ST_st8_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    axi_data_V_1_phi_fu_172_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, axi_data_V_1_reg_169, p_Val2_s_reg_216)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            axi_data_V_1_phi_fu_172_p4 <= p_Val2_s_reg_216;
        else 
            axi_data_V_1_phi_fu_172_p4 <= axi_data_V_1_reg_169;
        end if; 
    end process;

    brmerge_fu_308_p2 <= (sof_1_fu_84 or eol_phi_fu_195_p4);

    eol_1_phi_fu_161_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, eol_1_reg_158, axi_last_V_2_reg_203)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            eol_1_phi_fu_161_p4 <= axi_last_V_2_reg_203;
        else 
            eol_1_phi_fu_161_p4 <= eol_1_reg_158;
        end if; 
    end process;


    eol_phi_fu_195_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, eol_reg_191, axi_last_V_2_reg_203)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            eol_phi_fu_195_p4 <= axi_last_V_2_reg_203;
        else 
            eol_phi_fu_195_p4 <= eol_reg_191;
        end if; 
    end process;

    exitcond2_fu_281_p2 <= "1" when (p_s_reg_147 = ap_const_lv5_1C) else "0";
    exitcond3_fu_293_p2 <= "1" when (p_1_reg_180 = ap_const_lv5_1C) else "0";
    i_V_fu_287_p2 <= std_logic_vector(unsigned(p_s_reg_147) + unsigned(ap_const_lv5_1));

    img_data_stream_0_V_blk_n_assign_proc : process(img_data_stream_0_V_full_n, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            img_data_stream_0_V_blk_n <= img_data_stream_0_V_full_n;
        else 
            img_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_0_V_din <= tmp_104_reg_385;

    img_data_stream_0_V_write_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, ap_sig_127, ap_sig_137)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
            img_data_stream_0_V_write <= ap_const_logic_1;
        else 
            img_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_1_V_blk_n_assign_proc : process(img_data_stream_1_V_full_n, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            img_data_stream_1_V_blk_n <= img_data_stream_1_V_full_n;
        else 
            img_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_1_V_din <= tmp_4_reg_390;

    img_data_stream_1_V_write_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, ap_sig_127, ap_sig_137)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
            img_data_stream_1_V_write <= ap_const_logic_1;
        else 
            img_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_2_V_blk_n_assign_proc : process(img_data_stream_2_V_full_n, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond3_reg_372)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372))) then 
            img_data_stream_2_V_blk_n <= img_data_stream_2_V_full_n;
        else 
            img_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_2_V_din <= tmp_5_reg_395;

    img_data_stream_2_V_write_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond3_reg_372, ap_sig_127, ap_sig_137)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond3_reg_372) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_127) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_137))))) then 
            img_data_stream_2_V_write <= ap_const_logic_1;
        else 
            img_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_299_p2 <= std_logic_vector(unsigned(p_1_reg_180) + unsigned(ap_const_lv5_1));

    p_Val2_s_phi_fu_220_p4_assign_proc : process(AXI_video_strm_TDATA, brmerge_fu_308_p2, axi_data_V_1_phi_fu_172_p4, ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0, ap_sig_215)
    begin
        if (ap_sig_215) then
            if (not((ap_const_lv1_0 = brmerge_fu_308_p2))) then 
                p_Val2_s_phi_fu_220_p4 <= axi_data_V_1_phi_fu_172_p4;
            elsif ((ap_const_lv1_0 = brmerge_fu_308_p2)) then 
                p_Val2_s_phi_fu_220_p4 <= AXI_video_strm_TDATA;
            else 
                p_Val2_s_phi_fu_220_p4 <= ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
            end if;
        else 
            p_Val2_s_phi_fu_220_p4 <= ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0;
        end if; 
    end process;

    tmp_104_fu_314_p1 <= p_Val2_s_phi_fu_220_p4(8 - 1 downto 0);
    tmp_user_V_fu_272_p1 <= AXI_video_strm_TUSER;
end behav;
