// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "net_AXIvideo2Mat_32_28_28_4096_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic net_AXIvideo2Mat_32_28_28_4096_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic net_AXIvideo2Mat_32_28_28_4096_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_pp1_stg0_fsm_4 = "10000";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st7_fsm_5 = "100000";
const sc_lv<7> net_AXIvideo2Mat_32_28_28_4096_s::ap_ST_st8_fsm_6 = "1000000";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv1_1 = "1";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_1 = "1";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_4 = "100";
const sc_lv<1> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv1_0 = "0";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_5 = "101";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_3 = "11";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_6 = "110";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_2 = "10";
const sc_lv<5> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv5_0 = "00000";
const sc_lv<5> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv5_1C = "11100";
const sc_lv<5> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv5_1 = "1";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_8 = "1000";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_F = "1111";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_10 = "10000";
const sc_lv<32> net_AXIvideo2Mat_32_28_28_4096_s::ap_const_lv32_17 = "10111";
const bool net_AXIvideo2Mat_32_28_28_4096_s::ap_true = true;

net_AXIvideo2Mat_32_28_28_4096_s::net_AXIvideo2Mat_32_28_28_4096_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXI_video_strm_TDATA_blk_n);
    sensitive << ( AXI_video_strm_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( brmerge_fu_308_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( eol_2_reg_252 );

    SC_METHOD(thread_AXI_video_strm_TREADY);
    sensitive << ( AXI_video_strm_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( brmerge_fu_308_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_5 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );
    sensitive << ( ap_sig_155 );
    sensitive << ( eol_2_reg_252 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( exitcond2_fu_281_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_281_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0);

    SC_METHOD(thread_ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0);

    SC_METHOD(thread_ap_sig_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_127);
    sensitive << ( AXI_video_strm_TVALID );
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( brmerge_fu_308_p2 );

    SC_METHOD(thread_ap_sig_137);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( exitcond3_reg_372 );

    SC_METHOD(thread_ap_sig_145);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_ap_sig_155);
    sensitive << ( AXI_video_strm_TVALID );
    sensitive << ( eol_2_reg_252 );

    SC_METHOD(thread_ap_sig_173);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_180);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_200);
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( brmerge_fu_308_p2 );

    SC_METHOD(thread_ap_sig_215);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond3_fu_293_p2 );

    SC_METHOD(thread_ap_sig_24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_63);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_76);
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( brmerge_fu_308_p2 );

    SC_METHOD(thread_ap_sig_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg0_fsm_4);
    sensitive << ( ap_sig_63 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_24 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_180 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_5);
    sensitive << ( ap_sig_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_6);
    sensitive << ( ap_sig_173 );

    SC_METHOD(thread_axi_data_V_1_phi_fu_172_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( axi_data_V_1_reg_169 );
    sensitive << ( p_Val2_s_reg_216 );

    SC_METHOD(thread_brmerge_fu_308_p2);
    sensitive << ( eol_phi_fu_195_p4 );
    sensitive << ( sof_1_fu_84 );

    SC_METHOD(thread_eol_1_phi_fu_161_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( eol_1_reg_158 );
    sensitive << ( axi_last_V_2_reg_203 );

    SC_METHOD(thread_eol_phi_fu_195_p4);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( eol_reg_191 );
    sensitive << ( axi_last_V_2_reg_203 );

    SC_METHOD(thread_exitcond2_fu_281_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_s_reg_147 );

    SC_METHOD(thread_exitcond3_fu_293_p2);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( p_1_reg_180 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_i_V_fu_287_p2);
    sensitive << ( p_s_reg_147 );

    SC_METHOD(thread_img_data_stream_0_V_blk_n);
    sensitive << ( img_data_stream_0_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );

    SC_METHOD(thread_img_data_stream_0_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );
    sensitive << ( tmp_104_reg_385 );

    SC_METHOD(thread_img_data_stream_0_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_img_data_stream_1_V_blk_n);
    sensitive << ( img_data_stream_1_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );

    SC_METHOD(thread_img_data_stream_1_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );
    sensitive << ( tmp_4_reg_390 );

    SC_METHOD(thread_img_data_stream_1_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_img_data_stream_2_V_blk_n);
    sensitive << ( img_data_stream_2_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );

    SC_METHOD(thread_img_data_stream_2_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );
    sensitive << ( tmp_5_reg_395 );

    SC_METHOD(thread_img_data_stream_2_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_reg_372 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_j_V_fu_299_p2);
    sensitive << ( p_1_reg_180 );

    SC_METHOD(thread_p_Val2_s_phi_fu_220_p4);
    sensitive << ( AXI_video_strm_TDATA );
    sensitive << ( brmerge_fu_308_p2 );
    sensitive << ( axi_data_V_1_phi_fu_172_p4 );
    sensitive << ( ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0 );
    sensitive << ( ap_sig_215 );

    SC_METHOD(thread_tmp_104_fu_314_p1);
    sensitive << ( p_Val2_s_phi_fu_220_p4 );

    SC_METHOD(thread_tmp_user_V_fu_272_p1);
    sensitive << ( AXI_video_strm_TUSER );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( AXI_video_strm_TVALID );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( exitcond2_fu_281_p2 );
    sensitive << ( ap_sig_127 );
    sensitive << ( ap_sig_137 );
    sensitive << ( ap_sig_155 );
    sensitive << ( eol_2_reg_252 );
    sensitive << ( tmp_user_V_fu_272_p1 );

    ap_CS_fsm = "0000001";
    ap_reg_ppiten_pp1_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "net_AXIvideo2Mat_32_28_28_4096_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, AXI_video_strm_TDATA, "(port)AXI_video_strm_TDATA");
    sc_trace(mVcdFile, AXI_video_strm_TVALID, "(port)AXI_video_strm_TVALID");
    sc_trace(mVcdFile, AXI_video_strm_TREADY, "(port)AXI_video_strm_TREADY");
    sc_trace(mVcdFile, AXI_video_strm_TKEEP, "(port)AXI_video_strm_TKEEP");
    sc_trace(mVcdFile, AXI_video_strm_TSTRB, "(port)AXI_video_strm_TSTRB");
    sc_trace(mVcdFile, AXI_video_strm_TUSER, "(port)AXI_video_strm_TUSER");
    sc_trace(mVcdFile, AXI_video_strm_TLAST, "(port)AXI_video_strm_TLAST");
    sc_trace(mVcdFile, AXI_video_strm_TID, "(port)AXI_video_strm_TID");
    sc_trace(mVcdFile, AXI_video_strm_TDEST, "(port)AXI_video_strm_TDEST");
    sc_trace(mVcdFile, img_data_stream_0_V_din, "(port)img_data_stream_0_V_din");
    sc_trace(mVcdFile, img_data_stream_0_V_full_n, "(port)img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_data_stream_0_V_write, "(port)img_data_stream_0_V_write");
    sc_trace(mVcdFile, img_data_stream_1_V_din, "(port)img_data_stream_1_V_din");
    sc_trace(mVcdFile, img_data_stream_1_V_full_n, "(port)img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_data_stream_1_V_write, "(port)img_data_stream_1_V_write");
    sc_trace(mVcdFile, img_data_stream_2_V_din, "(port)img_data_stream_2_V_din");
    sc_trace(mVcdFile, img_data_stream_2_V_full_n, "(port)img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_data_stream_2_V_write, "(port)img_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_24, "ap_sig_24");
    sc_trace(mVcdFile, AXI_video_strm_TDATA_blk_n, "AXI_video_strm_TDATA_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_56, "ap_sig_56");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg0_fsm_4, "ap_sig_cseq_ST_pp1_stg0_fsm_4");
    sc_trace(mVcdFile, ap_sig_63, "ap_sig_63");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it0, "ap_reg_ppiten_pp1_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it1, "ap_reg_ppiten_pp1_it1");
    sc_trace(mVcdFile, exitcond3_fu_293_p2, "exitcond3_fu_293_p2");
    sc_trace(mVcdFile, brmerge_fu_308_p2, "brmerge_fu_308_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_5, "ap_sig_cseq_ST_st7_fsm_5");
    sc_trace(mVcdFile, ap_sig_83, "ap_sig_83");
    sc_trace(mVcdFile, img_data_stream_0_V_blk_n, "img_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, exitcond3_reg_372, "exitcond3_reg_372");
    sc_trace(mVcdFile, img_data_stream_1_V_blk_n, "img_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_2_V_blk_n, "img_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, eol_1_reg_158, "eol_1_reg_158");
    sc_trace(mVcdFile, axi_data_V_1_reg_169, "axi_data_V_1_reg_169");
    sc_trace(mVcdFile, p_1_reg_180, "p_1_reg_180");
    sc_trace(mVcdFile, eol_reg_191, "eol_reg_191");
    sc_trace(mVcdFile, axi_last_V_2_reg_203, "axi_last_V_2_reg_203");
    sc_trace(mVcdFile, p_Val2_s_reg_216, "p_Val2_s_reg_216");
    sc_trace(mVcdFile, tmp_data_V_reg_343, "tmp_data_V_reg_343");
    sc_trace(mVcdFile, tmp_last_V_reg_351, "tmp_last_V_reg_351");
    sc_trace(mVcdFile, exitcond2_fu_281_p2, "exitcond2_fu_281_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_122, "ap_sig_122");
    sc_trace(mVcdFile, i_V_fu_287_p2, "i_V_fu_287_p2");
    sc_trace(mVcdFile, i_V_reg_367, "i_V_reg_367");
    sc_trace(mVcdFile, ap_sig_127, "ap_sig_127");
    sc_trace(mVcdFile, ap_sig_137, "ap_sig_137");
    sc_trace(mVcdFile, j_V_fu_299_p2, "j_V_fu_299_p2");
    sc_trace(mVcdFile, tmp_104_fu_314_p1, "tmp_104_fu_314_p1");
    sc_trace(mVcdFile, tmp_104_reg_385, "tmp_104_reg_385");
    sc_trace(mVcdFile, tmp_4_reg_390, "tmp_4_reg_390");
    sc_trace(mVcdFile, tmp_5_reg_395, "tmp_5_reg_395");
    sc_trace(mVcdFile, ap_sig_155, "ap_sig_155");
    sc_trace(mVcdFile, axi_last_V_3_reg_228, "axi_last_V_3_reg_228");
    sc_trace(mVcdFile, axi_last_V1_reg_127, "axi_last_V1_reg_127");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_6, "ap_sig_cseq_ST_st8_fsm_6");
    sc_trace(mVcdFile, ap_sig_173, "ap_sig_173");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_180, "ap_sig_180");
    sc_trace(mVcdFile, axi_data_V_3_reg_240, "axi_data_V_3_reg_240");
    sc_trace(mVcdFile, axi_data_V1_reg_137, "axi_data_V1_reg_137");
    sc_trace(mVcdFile, p_s_reg_147, "p_s_reg_147");
    sc_trace(mVcdFile, eol_1_phi_fu_161_p4, "eol_1_phi_fu_161_p4");
    sc_trace(mVcdFile, axi_data_V_1_phi_fu_172_p4, "axi_data_V_1_phi_fu_172_p4");
    sc_trace(mVcdFile, eol_phi_fu_195_p4, "eol_phi_fu_195_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0, "ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0, "ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0");
    sc_trace(mVcdFile, p_Val2_s_phi_fu_220_p4, "p_Val2_s_phi_fu_220_p4");
    sc_trace(mVcdFile, eol_2_reg_252, "eol_2_reg_252");
    sc_trace(mVcdFile, sof_1_fu_84, "sof_1_fu_84");
    sc_trace(mVcdFile, tmp_user_V_fu_272_p1, "tmp_user_V_fu_272_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_76, "ap_sig_76");
    sc_trace(mVcdFile, ap_sig_200, "ap_sig_200");
    sc_trace(mVcdFile, ap_sig_145, "ap_sig_145");
    sc_trace(mVcdFile, ap_sig_215, "ap_sig_215");
#endif

    }
}

net_AXIvideo2Mat_32_28_28_4096_s::~net_AXIvideo2Mat_32_28_28_4096_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && 
             !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
             esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
                     !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && 
                     !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_data_V1_reg_137 = tmp_data_V_reg_343.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_data_V1_reg_137 = axi_data_V_3_reg_240.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        axi_data_V_1_reg_169 = p_Val2_s_reg_216.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
        axi_data_V_1_reg_169 = axi_data_V1_reg_137.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && 
         !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
        axi_data_V_3_reg_240 = axi_data_V_1_phi_fu_172_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && 
                !ap_sig_155.read())) {
        axi_data_V_3_reg_240 = AXI_video_strm_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        axi_last_V1_reg_127 = tmp_last_V_reg_351.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        axi_last_V1_reg_127 = axi_last_V_3_reg_228.read();
    }
    if (ap_sig_145.read()) {
        if (ap_sig_200.read()) {
            axi_last_V_2_reg_203 = eol_1_phi_fu_161_p4.read();
        } else if (ap_sig_76.read()) {
            axi_last_V_2_reg_203 = AXI_video_strm_TLAST.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            axi_last_V_2_reg_203 = ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && 
         !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
        axi_last_V_3_reg_228 = eol_1_phi_fu_161_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && 
                !ap_sig_155.read())) {
        axi_last_V_3_reg_228 = AXI_video_strm_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        eol_1_reg_158 = axi_last_V_2_reg_203.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
        eol_1_reg_158 = axi_last_V1_reg_127.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && 
         !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
        eol_2_reg_252 = eol_phi_fu_195_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && 
                !ap_sig_155.read())) {
        eol_2_reg_252 = AXI_video_strm_TLAST.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        eol_reg_191 = axi_last_V_2_reg_203.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
        eol_reg_191 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        p_1_reg_180 = j_V_fu_299_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
        p_1_reg_180 = ap_const_lv5_0;
    }
    if (ap_sig_145.read()) {
        if (ap_sig_200.read()) {
            p_Val2_s_reg_216 = axi_data_V_1_phi_fu_172_p4.read();
        } else if (ap_sig_76.read()) {
            p_Val2_s_reg_216 = AXI_video_strm_TDATA.read();
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            p_Val2_s_reg_216 = ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        p_s_reg_147 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_6.read())) {
        p_s_reg_147 = i_V_reg_367.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        sof_1_fu_84 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        sof_1_fu_84 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        exitcond3_reg_372 = exitcond3_fu_293_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_V_reg_367 = i_V_fu_287_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        tmp_104_reg_385 = tmp_104_fu_314_p1.read();
        tmp_4_reg_390 = p_Val2_s_phi_fu_220_p4.read().range(15, 8);
        tmp_5_reg_395 = p_Val2_s_phi_fu_220_p4.read().range(23, 16);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0))) {
        tmp_data_V_reg_343 = AXI_video_strm_TDATA.read();
        tmp_last_V_reg_351 = AXI_video_strm_TLAST.read();
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_AXI_video_strm_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read())))) {
        AXI_video_strm_TDATA_blk_n = AXI_video_strm_TVALID.read();
    } else {
        AXI_video_strm_TDATA_blk_n = ap_const_logic_1;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_AXI_video_strm_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && 
          !ap_sig_155.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read()))))) {
        AXI_video_strm_TREADY = ap_const_logic_1;
    } else {
        AXI_video_strm_TREADY = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0() {
    ap_reg_phiprechg_axi_last_V_2_reg_203pp1_it0 =  (sc_lv<1>) ("X");
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0() {
    ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_122() {
    ap_sig_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_127() {
    ap_sig_127 = (esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read()) && esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_137() {
    ap_sig_137 = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
  esl_seteq<1,1,1>(img_data_stream_0_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
  esl_seteq<1,1,1>(img_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
  esl_seteq<1,1,1>(img_data_stream_2_V_full_n.read(), ap_const_logic_0)));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_145() {
    ap_sig_145 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_155() {
    ap_sig_155 = (esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_173() {
    ap_sig_173 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_180() {
    ap_sig_180 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_200() {
    ap_sig_200 = (esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read()));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_215() {
    ap_sig_215 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_24() {
    ap_sig_24 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_56() {
    ap_sig_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_63() {
    ap_sig_63 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_76() {
    ap_sig_76 = (esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read()));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_83() {
    ap_sig_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_pp1_stg0_fsm_4() {
    if (ap_sig_63.read()) {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_24.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_56.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_180.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_122.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st7_fsm_5() {
    if (ap_sig_83.read()) {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_sig_cseq_ST_st8_fsm_6() {
    if (ap_sig_173.read()) {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_axi_data_V_1_phi_fu_172_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        axi_data_V_1_phi_fu_172_p4 = p_Val2_s_reg_216.read();
    } else {
        axi_data_V_1_phi_fu_172_p4 = axi_data_V_1_reg_169.read();
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_brmerge_fu_308_p2() {
    brmerge_fu_308_p2 = (sof_1_fu_84.read() | eol_phi_fu_195_p4.read());
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_eol_1_phi_fu_161_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        eol_1_phi_fu_161_p4 = axi_last_V_2_reg_203.read();
    } else {
        eol_1_phi_fu_161_p4 = eol_1_reg_158.read();
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_eol_phi_fu_195_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        eol_phi_fu_195_p4 = axi_last_V_2_reg_203.read();
    } else {
        eol_phi_fu_195_p4 = eol_reg_191.read();
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_exitcond2_fu_281_p2() {
    exitcond2_fu_281_p2 = (!p_s_reg_147.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_147.read() == ap_const_lv5_1C);
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_exitcond3_fu_293_p2() {
    exitcond3_fu_293_p2 = (!p_1_reg_180.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_180.read() == ap_const_lv5_1C);
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_i_V_fu_287_p2() {
    i_V_fu_287_p2 = (!p_s_reg_147.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(p_s_reg_147.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        img_data_stream_0_V_blk_n = img_data_stream_0_V_full_n.read();
    } else {
        img_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_0_V_din() {
    img_data_stream_0_V_din = tmp_104_reg_385.read();
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        img_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_data_stream_0_V_write = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        img_data_stream_1_V_blk_n = img_data_stream_1_V_full_n.read();
    } else {
        img_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_1_V_din() {
    img_data_stream_1_V_din = tmp_4_reg_390.read();
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        img_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_data_stream_1_V_write = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()))) {
        img_data_stream_2_V_blk_n = img_data_stream_2_V_full_n.read();
    } else {
        img_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_2_V_din() {
    img_data_stream_2_V_din = tmp_5_reg_395.read();
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_img_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_reg_372.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())))) {
        img_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_data_stream_2_V_write = ap_const_logic_0;
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_j_V_fu_299_p2() {
    j_V_fu_299_p2 = (!p_1_reg_180.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(p_1_reg_180.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_p_Val2_s_phi_fu_220_p4() {
    if (ap_sig_215.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read())) {
            p_Val2_s_phi_fu_220_p4 = axi_data_V_1_phi_fu_172_p4.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, brmerge_fu_308_p2.read())) {
            p_Val2_s_phi_fu_220_p4 = AXI_video_strm_TDATA.read();
        } else {
            p_Val2_s_phi_fu_220_p4 = ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0.read();
        }
    } else {
        p_Val2_s_phi_fu_220_p4 = ap_reg_phiprechg_p_Val2_s_reg_216pp1_it0.read();
    }
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_tmp_104_fu_314_p1() {
    tmp_104_fu_314_p1 = p_Val2_s_phi_fu_220_p4.read().range(8-1, 0);
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_tmp_user_V_fu_272_p1() {
    tmp_user_V_fu_272_p1 = AXI_video_strm_TUSER.read();
}

void net_AXIvideo2Mat_32_28_28_4096_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_272_p1.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else if ((!esl_seteq<1,1,1>(AXI_video_strm_TVALID.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_272_p1.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_281_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_127.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
  ap_sig_137.read())) && !esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()) && !ap_sig_155.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            } else if ((!ap_sig_155.read() && !esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_reg_252.read()))) {
                ap_NS_fsm = ap_ST_st8_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_5;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

